### ISSUE TITLE
var arr = new[] { 1, 2, 3, 4 };语法的支持

### ISSUE THREAD

**Issue by mybios** [yanghuan/CSharp.lua#1]
var arr = new[] { 1, 2, 3, 4 };
这种语法不支持
VisitImplicitArrayCreationExpression
这个没实现

**Comment by yanghuan** [comment]
嗯，多谢报告，后面会处理

**Comment by yanghuan** [comment]
https://github.com/yanghuan/CSharp.lua/commit/714b4898c5f123281fb6bd2100e425d12d93f4a1
已经处理
