### ISSUE TITLE
这种情况，会导致类初始化失败

### ISSUE THREAD

**Issue by mybios** [yanghuan/CSharp.lua#103]
类在manifest中的顺序不确定，泛型实例化时用到了一些尚未初始化的类，导致报错
C#代码
`
public class AliActionContainer<T> where T : AliAction
{
    public AliSafeList<T> actions = new AliSafeList<T>();
}

// 这个泛型实例化
public class AliActionContainer : AliActionContainer<object>
{

}

public AliSafeList<T>
{
}

`

执行失败：
LuaException: CompiledScripts/1_Fundation/Action/AliActionContainer:16: attempt to call a nil value (global 'AliSafeList_1')
stack traceback:
	CompiledScripts/1_Fundation/Action/AliActionContainer:16: in upvalue 'cls'
	CoreSystemLua/CoreSystem/Core:262: in field 'AliActionContainer_1'
	CompiledScripts/1_Fundation/Action/AliActionContainer:78: in local 'extends'
	CoreSystemLua/CoreSystem/Core:185: in upvalue 'setBase'
	CoreSystemLua/CoreSystem/Core:281: in function <CoreSystemLua/CoreSystem/Core:251>
	(...tail calls...)
	CoreSystemLua/CoreSystem/Core:1160: in field 'init'
	CompiledScripts/manifest:1110: in function 'CompiledScripts.manifest'
	Classloader:10: in main chunk
	[C]: in function 'require'
	Main.lua:1: in main chunk

**Comment by yanghuan** [comment]
代码片段不完整，提供下完整的代码结构

**Comment by mybios** [comment]
> 代码片段不完整，提供下完整的代码结构

上传了测试用例 #105
