### ISSUE TITLE
c#的string.Split转换

### ISSUE THREAD

**Issue by lostplesed** [yanghuan/CSharp.lua#11]
string a = "a, b";
string[] aa = a.Split(',');

转换成
local a = "a, b"
local aa = a:Split(44 --[[',']])

在CoreSystem/String.lua的函数String.Split中会使用到这个传入的44
然后调用44:gsub("([%%%^%.])", "%%%1")

应该直接转换为
local a = "a, b"
local aa = a:Split(',')
就对了

**Comment by yanghuan** [comment]
多谢反馈，已经修正
8bd487a2e899ff9a2b66afa841780ad3d8587fb0
