### ISSUE TITLE
找不到System.Runtime,Version=4.2.0.0

### ISSUE THREAD

**Issue by czlilove** [yanghuan/CSharp.lua#111]
未经处理的异常:  System.IO.FileNotFoundException: 未能加载文件或程序集“System.Runtime,Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”或它
的某一个依赖项。系统找不到指定的文件。

**Comment by yanghuan** [comment]
是否安装了.net core 2.0+ 运行环境？  或者命令行参数有问题？

**Comment by czlilove** [comment]
C:\Users\XXX>C:\Users\XXX\Desktop\CSharp.lua-1.2\CSharp.lua\
rp.lua.Launcher.dll -h           命令行参数是这样的，只是查看一下help.至于是否安装了.net core 2.0+运行环境，这个怎么看？

**Comment by yanghuan** [comment]
实例是这样的, 你需要dotnet程序，安装.net core,即可  https://dotnet.microsoft.com/download
D:\>dotnet CSharp.Lua.Launcher.dll -h

**Comment by czlilove** [comment]
![image](https://user-images.githubusercontent.com/25604083/50807987-7b0ba300-1337-11e9-8673-ab6a9b1a8ad8.png)
安装后还是报同样的错

**Comment by yanghuan** [comment]
嗯，试用的Google Cloud到期了，正在想办法处理

**Comment by czlilove** [comment]
非常感谢作者热心解答
