### ISSUE TITLE
c#变长参数转换问题

### ISSUE THREAD

**Issue by lostplesed** [yanghuan/CSharp.lua#13]
**c#**
void func(int a, params int[] args) {
            if (Array.IndexOf(args, 1) > -1) {
                a = 2;
            }
}

**lua**
func = function (a, args) 
      if System.Array.IndexOf(args, 1) > - 1 then
        a = 2
      end
end

转换完的结果应该是不对的 变长参数应该放到{...}里面

ps：感谢你的项目，现在手头的一个unity3d客户端游戏在转c#逻辑到lua代码，大量用了这个项目的自动转换代码，你修复的真快！再次感谢。

**Comment by yanghuan** [comment]
C#中不定参数，自动包装成数组，转换成lua，也是在调用端处理成数组。如下所示，处理成lua的不定参数形式(...)，无法满足C#中的接口规则。

C#
```
public static void Main() {
  test(1, 2, 3, 4);
}
public static void test(params int[] args) {
}
```
Lua
```
Main = function () 
  test(System.Array(System.Int)(1, 2, 3, 4))
end
test = function (args) 
end
```

**Comment by foxlively** [comment]
同样非常感谢你的项目, 我们的一个小unity项目打算用xlua做热更新, 看上去,配合你这个项目将需要hotfix的c#转为lua正合适.

**Comment by lostplesed** [comment]
原来是这样，明白了。我们项目也是用的xlua，预设中绑定的脚本和CoreSystem.lua公用的，转c#代码前移除非.net库依赖，只是把战斗的数值计算逻辑转成了lua代码所以基本依赖的不多，这套代码到时候还要跑在服务器那边做结果验证逻辑。
