### ISSUE TITLE
Question: Nullable and struct support? Generics?

### ISSUE THREAD

**Issue by AqlaSolutions** [yanghuan/CSharp.lua#14]
Hi, first - thank you for your work!

What's exactly with nullable support? You mentioned in FAQ that it doesn't work, I don't see why it's hard to implement.

Structs - do they work? I mean copying with assignment and passing argument "by value".

What class is directly translated to lua's hashtable class?

Are generic collections supported?

Are custom generic classes supported?

**Comment by yanghuan** [comment]
Nullable  Support incomplete.
Structs  & generic is Available

**Comment by AqlaSolutions** [comment]
Can you describe what's incomplete in nullables please?

**Comment by yanghuan** [comment]
```lua
local emptyFn = function() end
local falseFn = function() return false end
debug.setmetatable(nil, {
  __concat = function(a, b)
    if a == nil then
      if b == nil then
        return ""
      else
        return b
      end
    else
      return a
    end
  end,
  __add = emptyFn,
  __sub = emptyFn,
  __mul = emptyFn,
  __div = emptyFn,
  __mod = emptyFn,
  __unm = emptyFn,
  __lt = falseFn,
  __le = falseFn,
})
```
i just use this code to support nullable. in my coede, like int? bool?, i use very little,  so I didn't work on it.

**Comment by yanghuan** [comment]
a5890a0b7afbfbd47b9779ba484e12d28d5a8d20
support Nullable
