### ISSUE TITLE
Generate interfaces for lua library?

### ISSUE THREAD

**Issue by AqlaSolutions** [yanghuan/CSharp.lua#15]
Is there any tool or possibility to generate C# wrapper API for existing lua library? They could return dynamic but at least I have IntelliSense for class names, method and parameter names.

**Comment by yanghuan** [comment]
maybe you can write a empty .NET library, Used to provide an interface

**Comment by AqlaSolutions** [comment]
@yanghuan of course, but I'm thinking of generating it automatically.

**Comment by yanghuan** [comment]
#21
