### ISSUE TITLE
How can I use native lua methods from C#?

### ISSUE THREAD

**Issue by AqlaSolutions** [yanghuan/CSharp.lua#16]
I mean methods like `load`, `require`, etc

**Comment by yanghuan** [comment]
maybe you can write a empty .NET library, Used to provide an interface ...
it must be C# code, now there is no library can do this, I'm sorry

**Comment by AqlaSolutions** [comment]
I think this is covered by the https://github.com/yanghuan/CSharp.lua/issues/21 and https://github.com/yanghuan/CSharp.lua/issues/15
