### ISSUE TITLE
meta xml请求支持field的get和set模板代码生成

### ISSUE THREAD

**Issue by mybios** [yanghuan/CSharp.lua#174]
我希望meta xml能以这种写法：
				\<field name="particleScale"\>
					\<get Template="{this}:getparticleScale()"/\>
					\<set Template="{this}:setparticleScale({0})"/\>
				\</field\>
这样生成的lua代码直接调用函数。
简化lua引擎的复杂度，提高执行效率。

**Comment by yanghuan** [comment]
配置成以下方式即可,可强制使用生成类似property的get, set方法来操作字段
<field name="particleScale" IsProperty=“true”  />
