### ISSUE TITLE
delegate不支持静态方法绑定

### ISSUE THREAD

**Issue by mybios** [yanghuan/CSharp.lua#177]
假如被绑定的方法是静态方法，会导致调用System.bind在__call时传入的参数出错

class Test
{
static void Call(int value)
{
if(value != 123) throw new Exception();
Console.Write("Called");
}

static void TestIt()
{
Action<int> action = Call;
action(123);
}
}

**Comment by yanghuan** [comment]
经过测试，未发现问题
