### ISSUE TITLE
Double-quoted -s -d arguments

### ISSUE THREAD

**Issue by AqlaSolutions** [yanghuan/CSharp.lua#18]
When there are spaces in an input or output directory the path should be passed like 

        -s "D:\Sources Folder" -d "D:\My Documents\Path"

 - with double quotes but it doesn't work now.

**Comment by yanghuan** [comment]
i test command with double quotes , it can work. can your report the error more detail?

**Comment by AqlaSolutions** [comment]
It outputs
    -d is not found

CSharp.lua.exe -s "D:\CSharp.lua\vlads-mods\vlads-programming-mod\" -d D:\CSharp.lua\vlads-mods\vlads-programming-mod\bin\Debug\..\lua\ -a

**Comment by yanghuan** [comment]
when i debug, i found  \"  is Transfer characters,
you should use "D:\CSharp.lua\vlads-mods\vlads-programming-mod\\"

**Comment by AqlaSolutions** [comment]
Uh, I didn't know it applies this way, thanks for checking!
