### ISSUE TITLE
Compilation Issue on weird arithmetic string

### ISSUE THREAD

**Issue by ogoguel** [yanghuan/CSharp.lua#180]
`a = b * +1` is a weird yet correct expression in C#

The code is transpiled "as is" in Lua, but unfortunately, does not compile ...

```
a = a * +1
input:1: unexpected symbol near '+'

```

Not a major bug, but a bug neverthless that could cripple an automated conversion process.

Nice project anyway ;:)

**Comment by yanghuan** [comment]
thanks report
