### ISSUE TITLE
一元否定(前置减号)表达式无法支持meta

### ISSUE THREAD

**Issue by mybios** [yanghuan/CSharp.lua#189]
meta里定义了：
`                <method name="op_UnaryNegation" GenericArgCount="0" ArgCount="1" Template="UnityEngine.Vector3.op_UnaryNegation({0})" >
                    <arg type="UnityEngine.Vector3">
                    </arg>
                </method>
`
C#代码
        Vector3 left = -owner.transform.right.normalized;

生成lua代码：
local left = - owner:gettransform():getright():getnormalized()

正确的应该是
local left = UnityEngine.Vector3.op_UnaryNegation(owner:gettransform():getright():getnormalized())

**Comment by yanghuan** [comment]
一元运算符未判断操作符重载，已经添加处理， 会生成默认方法调用，可以不使用meta
