### ISSUE TITLE
Class with many (>200) functions can't be used

### ISSUE THREAD

**Issue by zod** [yanghuan/CSharp.lua#197]
I have a generated C# class with many functions which is converted using CSharp.Lua but the lua interpreter fails to run the resulting script and prints (excerpt)
```
Snippet.lua:37: too many local variables (limit is 200) in function at line 12 near ','
```
because all methods are defined as local variables. Is there a way to use this class anyway?

**Comment by yanghuan** [comment]
Sorry, you need to refactor the C # code, and I haven't found a better and simpler way to fix it.
