### ISSUE TITLE
希望支持Attribute和简单的Reflect

### ISSUE THREAD

**Issue by mybios** [yanghuan/CSharp.lua#2]
希望可以在打了Attribute标签的元素上，有限的生成对应的Reflect元信息，能通过GetType().GetMember等方式把这些元信息取回来，如果没有打Attribute的元素，则可以不生成。要不然怕生成的元信息量太大了。
Attribute，可以用在很多地方，例如：
protobuf
dataconfig读取
数据绑定
UI绑定
等等很多可以大幅度精简逻辑代码的地方。

**Comment by yanghuan** [comment]
ok,已经收到

**Comment by yanghuan** [comment]
c6b7ab2e1f08776872bdc968e65e67d0ba6da824
已经支持，由于仅保存的了基本的元数据信息，API接口能支持的有限，但已经包最主要的几个接口了
