### ISSUE TITLE
能否支持Conditional来决定是否生成代码？

### ISSUE THREAD

**Issue by mybios** [yanghuan/CSharp.lua#207]
有些调试代码，或者日志代码，通过类似这样的方式编写
    [Conditional("UNITY_EDITOR")]
    public static void DrawMarker(Vector3 pos,float size,Color color,float dur,bool depthTest = true)
	{
}

在生成调用这个函数的代码，希望不生成具体调用的lua代码。

**Comment by yanghuan** [comment]
目前的话可以这样使用
```c#
  class Program {
    public static void Main(string[] args) {
#if !__CSharpLua__
      f();
#endif
    }

    /// <summary>
    /// @CSharpLua.Ignore
    /// </summary>
    public static void f() {

    }
  }
```
这样调用端和方法都不会生成

**Comment by yanghuan** [comment]
我考虑改下代码，让@CSharpLua.Ignore标注的方法，在调用端也不生成代码

**Comment by mybios** [comment]
Conditional是C#的标准吧？为何不能直接支持这种？

**Comment by mybios** [comment]
如果要通过宏#if的方式才支持的话，就失去了自动化的意义了。相当于手动处理所有调用。相当下，打日志都变成，将会多麻烦：
#if xxxx
Console.Log("xxx")
#endif

**Comment by mybios** [comment]
使用Conditional是能确保C#版跟lua版的语义是一致的，如果用 @CSharpLua.Ignore注释的方法，则无法保证。

**Comment by yanghuan** [comment]
好的，我看下Conditional属性，看下编译器规则

**Comment by mybios** [comment]
在我的包装代码生成中，有一段这样的roslyn代码，用来判断method是否有这个特性，从而忽略对应的包装代码生成与调用。
`
                foreach (var attr in originMethod.GetAttributes())
                {
                    if (attr.AttributeClass.GetFullName() == "System.Diagnostics.ConditionalAttribute")
                    {
                        IsIgnore = !context.settings.defines.Contains((string)attr.ConstructorArguments[0].Value);
                    }
                }
`
