### ISSUE TITLE
请求支持内联方法特性

### ISSUE THREAD

**Issue by mybios** [yanghuan/CSharp.lua#208]
C#中，通过对方法定义特性可以让这个方法内联展开在调用处。
[MethodImpl(MethodImplOptions.AggressiveInlining)]

在lua中，如果可以对一些简单的方法强制内联，则可以提高一些应用场景的性能。
所以，请求支持内联声明。

**Comment by yanghuan** [comment]
嗯，以前也有人提过，我尝试处理下
