### ISSUE TITLE
Calling an overloaded virtual method from a different module

### ISSUE THREAD

**Issue by DezZolation** [yanghuan/CSharp.lua#215]
Consider the following:

```cs
public static class Program {
    public static void Main() {
      A a = new A();
      a.MyMethod();
      B b = new B();
      b.MyMethod();
    }
  }

  public class A
  {
      public A(){}

      public virtual void MyMethod()
      {
          Console.WriteLine("Foo");
      }
  }

  public class B : A
  {
    public B(){}
    
    public override void MyMethod()
    {
        Console.WriteLine("Bar");
    }
  }
```
If this code is compiled in the same namespace, the result is that ``MyMethod`` is declared as the same function:
```Lua
 namespace.class("A", function (namespace)
    local MyMethod
    MyMethod = function (this)
      System.Console.WriteLine("Foo")
    end
    return {
      MyMethod = MyMethod
    }
  end)

  namespace.class("B", function (namespace)
    local MyMethod
    MyMethod = function (this)
      System.Console.WriteLine("Bar")
    end
    return {
      __inherits__ = function (out)
        return {
          out.HelloLua.A
        }
      end,
      MyMethod = MyMethod
    }
  end)
```
And the functions are called like so:
```Lua
    Main = function ()
      local a = HelloLua.A()
      a:MyMethod()
      local b = HelloLua.B()
      b:MyMethod()
    end
```
Everything good. However, if I put this code in a module and call ``MyMethod()`` from a different module then it is parsed like so:
```Lua
    Main = function ()
      local a = HelloLua.A()
      a:MyMethod1()
      local b = HelloLua.B()
      b:MyMethod()
    end
```

For some reason the base class ``A`` gets its ``MyMethod`` method parsed as ``MyMethod1()``, which doesn't exist.

Also, if my extended class ``B`` is declared in the same module from which I call ``A.MyMethod()`` then everything works correctly.

**Comment by yanghuan** [comment]
i test in latest code version, not found this error

**Comment by DezZolation** [comment]
Okay I'm going to reference the code in our project as an example. I see that a vital part that I might have missed out is that calling the base method is done from an inherited class as well.
The basic structure that I have:
![issue215](https://user-images.githubusercontent.com/11147160/56774203-f186c080-67c1-11e9-86f9-d8660828e4ad.jpg)

Calling ``FaceElement`` from ``WorldObject`` parses ``FaceElement1``, though the base method is called ``FaceElement``. ``Ped`` does call the correct method.

In our project. [This](https://github.com/mta-slipe/Slipe-Core/blob/7dcb65efc8d3e34c665807302ecfce6b551123ce/Source/ClientSide/Program.cs#L27) is where I call ``FaceElement`` on ``WorldObject``. Which should call [this](https://github.com/mta-slipe/Slipe-Core/blob/7dcb65efc8d3e34c665807302ecfce6b551123ce/Slipe/Core/Source/SlipeShared/Elements/PhysicalElement.cs#L482) virtual method.

And [this](https://github.com/mta-slipe/Slipe-Core/blob/7dcb65efc8d3e34c665807302ecfce6b551123ce/Source/ClientSide/Follower.cs#L48) is where I call ``FaceElement`` on ``Ped``. Which calls [this](https://github.com/mta-slipe/Slipe-Core/blob/7dcb65efc8d3e34c665807302ecfce6b551123ce/Slipe/Core/Source/SlipeShared/Peds/SharedPed.cs#L502) overriden method.

Note that the classes are defined outside of the module in which we call them. (Program.cs and Follower.cs are in a different module)

We are using the latest CSharp.lua version

**Comment by yanghuan** [comment]
I can't reproduce this mistake.Here's my Code.

This is a Project named Library
```
namespace Library {
  public class Element {
  }

  public abstract class PhysicalElement : Element {
    public virtual void FaceElement(int a) {
    }
  }

  public class SharedPed : PhysicalElement {
    public override void FaceElement(int a) {
    }
  }

  public class SharedWorldObject : PhysicalElement {
  }

}
```

This is a Project named LibraryUp
```
using System;
using Library;

namespace LibraryUp {
  public class WorldObject : SharedWorldObject {
  }

  public class Ped : SharedPed {

  }
}
```

This is a project Named Test
```
using LibraryUp;

namespace Test {
  public class Follower : Ped { }


  public static class ProgramTest {
    public static void MainTest() {
      var wo = new WorldObject();
      wo.FaceElement(2);

      var f = new Follower();
      f.FaceElement(2);

    }
  }
}
```
compiled will putout
```
-- Generated by CSharp.lua Compiler
local System = System
local LibraryUp = LibraryUp
local Test
System.import(function (out)
  Test = out.Test
end)
System.namespace("Test", function (namespace)
  namespace.class("Follower", function (namespace)
    return {
      __inherits__ = function (out)
        return {
          out.LibraryUp.Ped
        }
      end
    }
  end)


  namespace.class("ProgramTest", function (namespace)
    local MainTest
    MainTest = function ()
      local wo = LibraryUp.WorldObject()
      wo:FaceElement(2)

      local f = Test.Follower()
      f:FaceElement(2)
    end
    return {
      MainTest = MainTest
    }
  end)
end)

```
Dependencies are like this
Test -> LibraryUp -> Library

**Comment by DezZolation** [comment]
After many hours I finally managed to reproduce this issue in a seperate project.
I have created a repo where you can see this issue in action.

[https://github.com/DezZolation/Issue215](https://github.com/DezZolation/Issue215)

It appears that the ``!`` at the end to signify a module triggers this issue. If it is ommitted all is well.

You can see the method is named incorrectly at [this](https://github.com/DezZolation/Issue215/blob/1c62536c2d9659f9127b2ebf7ceed3e217489ece/dist/Issue215/Program.lua#L12) line.

I believe the compiler version I used is now just 2 commits behind the master due to your recent changes.

**Comment by yanghuan** [comment]
[Compiler.zip](https://github.com/yanghuan/CSharp.lua/files/3123859/Compiler.zip)
i found the compiler not latest, i test latest it is ok. you can download the zip and try it, it will be ok

**Comment by DezZolation** [comment]
Okay so the new compiler version did its job 🎉 
Excuse us for not keeping it all up to date
