### ISSUE TITLE
Assembly: Type.GetCustomAttributes inherit is incorrect

### ISSUE THREAD

**Issue by DezZolation** [yanghuan/CSharp.lua#218]
When using [Type.GetCustomAttributes(this, attributeType, inherit)](https://github.com/yanghuan/CSharp.lua/blob/2a7462196ba70a3f44c2243868a3d520d3b8048d/CSharp.lua/CoreSystem.Lua/CoreSystem/Reflection/Assembly.lua#L695), the ``inherit`` variable isn't applied correctly. If ``inherit`` is ``false``, it still inherits from all the parent classes as ``metadata = this[1].__metadata__`` searches for the ``__metadata__`` field in parent classes.

I managed to fix this locally by changing that line to:
```Lua
local metadata = rawget(this[1], "__metadata__")
```
But seeing as you don't use ``rawget`` anywhere else in this project, I think there is a better way to do this.
Also if ``inherit`` is true, that part of the method will just return duplicate results.

If you're okay with using ``rawget`` I can have a pull request ready quickly 👌. Otherwise let me know.

**Comment by yanghuan** [comment]
thanks you pull request, commit, i will merge it.
