### ISSUE TITLE
MetadataCustomAttributes index parameter unclear

### ISSUE THREAD

**Issue by DezZolation** [yanghuan/CSharp.lua#221]
In ``Assembly.lua``, the functions``fillMetadataCustomAttributes`` and ``isMetadataDefined`` require an ``index`` parameter. I don't understand the workings and the use of this parameter. I see that it does some magic on the numbers passed through the metadata tables but it always seems to pass incorrect results to the afformentioned functions. If one has defined multiple custom attributes then ``index`` can take values ``> 100``. However, the ``index`` parameter is later used in a loop:
```Lua
for i = index, #metadata do
```
``#metadata`` doesn't get big so the body of the loop is then never called.

I managed to get everything working by just setting ``index`` to ``1``. There must've been a thought behind this system but right now it doesn't work. Could you clarify?

**Comment by yanghuan** [comment]
AddMethodMetaData
https://github.com/yanghuan/CSharp.lua/blob/master/CSharp.lua/LuaSyntaxNodeTransform.cs#L573
AddFieldMetaData
https://github.com/yanghuan/CSharp.lua/blob/master/CSharp.lua/LuaSyntaxNodeTransform.cs#L757
AddPropertyOrEventMetaData
https://github.com/yanghuan/CSharp.lua/blob/master/CSharp.lua/LuaSyntaxNodeTransform.cs#L892

**Comment by DezZolation** [comment]
I understand the use of the second item as flags a bit more clearly now. I can deduce from the output that part of the flags represent the amount of parameters:
```Lua
methods = {
    { ".ctor", 0x306, __ctor1__, System.Numerics.Vector3, System.Boolean, System.Numerics.Vector2 },
    { ".ctor", 0x106, __ctor2__, out.Slipe.MtaDefinitions.MtaElement }
}
```

However, I still think something goes wrong in the usage at some places. Take the [getMethodAttributesIndex](https://github.com/yanghuan/CSharp.lua/blob/4df6136e12c6f3b44845511545d5989d1756c09e/CSharp.lua/CoreSystem.Lua/CoreSystem/Reflection/Assembly.lua#L362) function, it uses the flags to deduce ``typeParametersCount`` and ``parameterCount``.
In the above example you see that I can have the flag ``0x306``. The parameterCount is then determined by the ``bit and`` operation using ``0x300``. The result of this operation is ``0x300``, but you then use that result arithmatically with ``index = 4 + parameterCount``. The decimal representation of ``parameterCount`` is ``768``. This results in the fact that ``772`` is returned as the index. This cannot be correct or am I mistaken somewhere?
