### ISSUE TITLE
报错： Your code is startling,17 temporary variables is not enough, please refactor your code.

### ISSUE THREAD

**Issue by infosunny** [yanghuan/CSharp.lua#229]
我的文件内容如下：
`using System.Collections.Generic;

public class MyElement
{
public int value1;
public int value2;
public bool value3;
public string value4;
public string value5;

public MyElement()
{

}

}

public class MyClass
{

public MyClass()
{
    Init();
}

public void Init()
{
    Dictionary<int, List<MyElement>> dic = new Dictionary<int, List<MyElement>>{

        {1,
            new List<MyElement>()
            {
                new MyElement()
                {
                    value1 = 1,
                    value2 = 2,
                    value3 = true,
                    value4 = "A Dictionary<TKey,TValue> can support multiple readers concurrently",
                    value5 = "as long as the collection is not modified"
                }
            }

        },
        {2,
            new List<MyElement>()
            {
                new MyElement()
                {
                    value1 = 1,
                    value2 = 2,
                    value3 = true,
                    value4 = "A Dictionary<TKey,TValue> can support multiple readers concurrently",
                    value5 = "as long as the collection is not modified"
                }
            }

        },
        {3,
            new List<MyElement>()
            {
                new MyElement()
                {
                    value1 = 1,
                    value2 = 2,
                    value3 = true,
                    value4 = "A Dictionary<TKey,TValue> can support multiple readers concurrently",
                    value5 = "as long as the collection is not modified"
                }
            }

        },
        {4,
            new List<MyElement>()
            {
                new MyElement()
                {
                    value1 = 1,
                    value2 = 2,
                    value3 = true,
                    value4 = "A Dictionary<TKey,TValue> can support multiple readers concurrently",
                    value5 = "as long as the collection is not modified"
                }
            }

        },
        {5,
            new List<MyElement>()
            {
                new MyElement()
                {
                    value1 = 1,
                    value2 = 2,
                    value3 = true,
                    value4 = "A Dictionary<TKey,TValue> can support multiple readers concurrently",
                    value5 = "as long as the collection is not modified"
                }
            }

        },
        {6,
            new List<MyElement>()
            {
                new MyElement()
                {
                    value1 = 1,
                    value2 = 2,
                    value3 = true,
                    value4 = "A Dictionary<TKey,TValue> can support multiple readers concurrently",
                    value5 = "as long as the collection is not modified"
                }
            }

        },
        {7,
            new List<MyElement>()
            {
                new MyElement()
                {
                    value1 = 1,
                    value2 = 2,
                    value3 = true,
                    value4 = "A Dictionary<TKey,TValue> can support multiple readers concurrently",
                    value5 = "as long as the collection is not modified"
                }
            }

        },
        {8,
            new List<MyElement>()
            {
                new MyElement()
                {
                    value1 = 1,
                    value2 = 2,
                    value3 = true,
                    value4 = "A Dictionary<TKey,TValue> can support multiple readers concurrently",
                    value5 = "as long as the collection is not modified"
                }
            }

        },
        {9,
            new List<MyElement>()
            {
                new MyElement()
                {
                    value1 = 1,
                    value2 = 2,
                    value3 = true,
                    value4 = "A Dictionary<TKey,TValue> can support multiple readers concurrently",
                    value5 = "as long as the collection is not modified"
                }
            }

        },
        {10,
            new List<MyElement>()
            {
                new MyElement()
                {
                    value1 = 1,
                    value2 = 2,
                    value3 = true,
                    value4 = "A Dictionary<TKey,TValue> can support multiple readers concurrently",
                    value5 = "as long as the collection is not modified"
                }
            }

        },
        {11,
            new List<MyElement>()
            {
                new MyElement()
                {
                    value1 = 1,
                    value2 = 2,
                    value3 = true,
                    value4 = "A Dictionary<TKey,TValue> can support multiple readers concurrently",
                    value5 = "as long as the collection is not modified"
                }
            }

        },
        {12,
            new List<MyElement>()
            {
                new MyElement()
                {
                    value1 = 1,
                    value2 = 2,
                    value3 = true,
                    value4 = "A Dictionary<TKey,TValue> can support multiple readers concurrently",
                    value5 = "as long as the collection is not modified"
                }
            }

        },
        {13,
            new List<MyElement>()
            {
                new MyElement()
                {
                    value1 = 1,
                    value2 = 2,
                    value3 = true,
                    value4 = "A Dictionary<TKey,TValue> can support multiple readers concurrently",
                    value5 = "as long as the collection is not modified"
                }
            }

        },
        {14,
            new List<MyElement>()
            {
                new MyElement()
                {
                    value1 = 1,
                    value2 = 2,
                    value3 = true,
                    value4 = "A Dictionary<TKey,TValue> can support multiple readers concurrently",
                    value5 = "as long as the collection is not modified"
                }
            }

        },
        {15,
            new List<MyElement>()
            {
                new MyElement()
                {
                    value1 = 1,
                    value2 = 2,
                    value3 = true,
                    value4 = "A Dictionary<TKey,TValue> can support multiple readers concurrently",
                    value5 = "as long as the collection is not modified"
                }
            }

        }
    };
}

}
`
报错信息如下：
SourceLocation(/Users/infosunny/Documents/TestCsharpLua/Assets/Compiled/MyClass.cs@142:17)"new List()
{
new MyElement()
{
value1 = 1,
value2 = 2,
value3 = true,
value4 = "A Dictionary<TKey,TValue> can support multiple readers concurrently",
value5 = "as long as the collection is not modified"
}
}": Your code is startling,17 temporary variables is not enough, please refactor your code.

**Comment by yanghuan** [comment]
fix by aee59a864a5a4b4f29bf5a70e7f9ab457845edd6
