### ISSUE TITLE
Updating dependencies

### ISSUE THREAD

**Issue by AqlaSolutions** [yanghuan/CSharp.lua#23]
I discovered that you are using pretty outdated nuget dependencies, please consider updating.

**Comment by yanghuan** [comment]
the new version roslyn need a lot of packages , whice not in .net framework 4.6 or 4.7, if update will bring a lot of dll. when .net core 2.0 release, i will convert to .net core 2.0

**Comment by AqlaSolutions** [comment]
Cool, thanks!
