### ISSUE TITLE
class with 2 constructors only calls 1

### ISSUE THREAD

**Issue by greay** [yanghuan/CSharp.lua#238]
In this test, in BasicInkExample.lua, Story has 2 constructors. I call the public constructor, that takes a json string, but it looks like the one that ends up getting executed is the other one (in the C#, this constructor is marked as *internal*).

[ink-lua.zip](https://github.com/yanghuan/CSharp.lua/files/3538518/ink-lua.zip)

**Comment by yanghuan** [comment]
this code is not ouput by compiled
```
local story = Ink.Runtime.Story(inkJSONAsset)
```
should be
```
local story = System.new(Ink.Runtime.Story, 2, inkJSONAsset)
```
