### ISSUE TITLE
Ambiguous parsed syntax

### ISSUE THREAD

**Issue by DezZolation** [yanghuan/CSharp.lua#242]
Given:

```cs
TrackNode lsSwitch = railManager.Nodes[313];
((TrackSwitch) lsSwitch).Flip();
```

Parses to:

```Lua
local lsSwitch = this.railManager.Nodes:get(313)
(System.cast(SharedRails.TrackSwitch, lsSwitch)):Flip()
```

This produces the following syntax error:
```
Ambiguous Syntax (function call x new statement) near '('
```

This is a Lua syntax error as it recognizes ``...:get(313)`` followed by a statement within brackets ``(System.cast(..))`` and it is unsure if it needs to be a function call or not.

Adding a semicolon after the first statement would solve the problem.

**Comment by yanghuan** [comment]
i run this code not got the error
```
      int[] array = new int[100];
      object b = 2;
      int a = array[0];
      ((int)b).ToString();
````
Is there anything wrong ?
