### ISSUE TITLE
Multiple issues with Enums

### ISSUE THREAD

**Issue by DezZolation** [yanghuan/CSharp.lua#243]
1. `Enum.lua` gets the type of variable `TEnum` at line 161 but `TEnum` is already a type if the ``Enum.TryParse(Type type, ...)`` methos variant is used. Therefore the exception at line 56 is always thrown.

2. `Enum.IsDefined` errors with `String.lua:172: bad argument #1 to 'find' (string expected got boolean)

3. If the enum is defined in a different module, all of the above methods don't work anymore because the type parameter is nil.

Example:
```cs
            string a = "andre";
            if (Enum.TryParse(typeof(PedModel), a, true, out object b))
                Console.WriteLine((int)b);
```

With `PedModel` defined in a different module, it is always nil and the assertions fail.

**Comment by yanghuan** [comment]
add argument "-e" for solve 3

**Comment by yanghuan** [comment]
Question 2 I didn't konw it, could you provide more detailed information?
