### ISSUE TITLE
Incorrect float convertion

### ISSUE THREAD

**Issue by ogoguel** [yanghuan/CSharp.lua#249]
` float d = (float)Math.Sqrt(3);`

produces

` local d = System.ToSingle(math.Sqrt(3))`

instead of 

` local d = System.Convert.ToSingle(math.Sqrt(3))`

Tested in : https://yanghuan.github.io/external/bridgelua-editor/index.html

**Comment by yanghuan** [comment]
```
local d = System.ToSingle(math.Sqrt(3))
```
is the right code, What's the problem？ Can you provide more details information ?

**Comment by ogoguel** [comment]
`System.ToSingle` is indeed implemented in `Convert.Lua `, but I was wondering why you chose to implement the convert functions (`To*`) at the root of the `System `namespace instead of the `System.Convert `namespace as it is defined in C# ? (System.ToSingle does not exist in C#)

In a similar way, why convert `Math.Sqrt` to `math.Sqrt ` (with a lower m and an upper S) ? I would have expected either to be converted to the Lua math library (`math.sqrt`) or to be kept as the C# Format (`Math.Sqrt`)?

**Comment by yanghuan** [comment]
System.ToSingle has one less table check operation than System.Convert.ToSingle.And it's short and easier to read.

math.Sqrt & System.Math.Sqrt, It's the same.

**Comment by ogoguel** [comment]
Understood.

 I am using Lua on top of C# hence my recurrent thoughts about whether to use your Lua implementation (for speed) or C# binding/userdata (for compatibility) for the System namespace. 

If the converter was keeping the C# convention, it would be easier to switch between both, hence my question

Hope it clarifies!

**Comment by yanghuan** [comment]
The current treatment is entirely personal and very subjective, and thank you for your feedback
