### ISSUE TITLE
Suggestion: improve method for handling lua code insertion

### ISSUE THREAD

**Issue by Drake53** [yanghuan/CSharp.lua#264]
The current method to insert lua code is documented [here](https://github.com/yanghuan/CSharp.lua/wiki/FAQ_en#7how-do-you-call-or-insert-lua-code-in-your-code). It involves using comments, so there is no support for intellisense.

I have experimented with a different approach in my fork. An example:
```csharp
namespace CSharpLua.Api {
  public static class Lua {
    [LuaMember("print")]
    public static extern void Print(params object[] args);
  }
}
```
By marking a method with the extern keyword and a new attribute "LuaMemberAttribute", we declare this to be a lua function (or field). This allows us to now write:
```csharp
using static CSharpLua.Api.Lua;
void Test() {
  Print("hello world");

  // instead of:
  /*[[print('hello world')]]*/
}
```

This approach requires some changes in the compiler to check if a member has the LuaMemberAttribute.

I would like to hear what you think of this alternative approach. If you think it's a good idea, I can make a pull request later.

**Comment by yanghuan** [comment]
thanks  the feedback.
I add  @CSharpLua.Template attribute to support it. 
https://github.com/yanghuan/CSharp.lua/wiki/attributes_en#csharpluatemplate

This implementation is more consistent with the code that already exists

**Comment by Drake53** [comment]
I read the documentation but there are still some cases which I'm not sure are supported with your implementation:
1) Fields (for example math.pi)
2) Functions with multiple return values (for example pcall)
3) Is it possible to combine @CSharpLua.Template and actual documentation? I rather not have the former visible with intellisense, does it still work if I put the attribute in <remarks> for example?

Thank you for your time.

**Comment by yanghuan** [comment]
1)  “Fields (for example math.pi)”  support by 690790554ec500fba891ebf3995ca9b8e3cc9957
2) "Functions with multiple return values", it is supported, you can see https://github.com/yanghuan/CSharp.lua/blob/master/CSharp.lua/System.xml#L74
3) Implementation in document comments really doesn't have intellisense, use attribute to confirm that it is more appropriate. 

Initially considering that there is not much attribute required, the code that needs code in the comments does not require additional dependency。
in the future, maybe i will directly use C# attributes to support it.

**Comment by Drake53** [comment]
Thank you, I created some tests and it seems to be working. The only issue I still have is that it does not work if the lua method/field is declared in the same class as where it's used, for example:
```csharp
using System;
using System.Collections.Generic;
using System.Text;

namespace Test {
  class TestTranspileTemplate {
    /// @CSharpLua.Template = "math.pi"
    private static readonly float PI = 3.14f;

    private float _pi;

    public TestTranspileTemplate() {
      if (!PInvoke(() => { _pi = PI; }, out var error ) )
      {
        Print( error );
      }
    }

    /// @CSharpLua.Template = "print({0})"
    public static extern void Print(object a);
        
    /// @CSharpLua.Template = "pcall({0})"
    public static extern bool PInvoke(Action f, out string errorMessage);
  }
}
```

This then becomes:
```lua
      local default, error = PInvoke(function ()
        this._pi = PI
      end)
      if not default then
        Print(error)
      end
```
