### ISSUE TITLE
Unable to setmetatable on `string` as its read only

### ISSUE THREAD

**Issue by mchandler-manticore** [yanghuan/CSharp.lua#269]
Hi Yanghuan,

Thank you for making this epic project. Im trying to use it with a game engine that has the string meta table as readonly and currently loading the core library String.lua fails due to this. Is it possible to do String.lua in a different way that doesnt require modifying the string metatable?

**Comment by yanghuan** [comment]
string metatable  must add some field like __name__, maybe you can set string metatable __newindex to nil, it can workaround ?

**Comment by mchandler-manticore** [comment]
Looking at the game code that might work or else was thinking of generating helper functions in lua for strings (i.e. instead of ("abc"):ToLower() call StringToLower("abc") ). Thanks for the tip though.
