### ISSUE TITLE
[Suggestion] Support XmlMetaProvider.Deserialize for <doc> files

### ISSUE THREAD

**Issue by Drake53** [yanghuan/CSharp.lua#270]
When a method or field with the CSharpLua.Template attribute is located in a .dll (so it gets added through Compiler.libs_), the compiler ignores this attribute.

Example:
I add a reference to package War3Api.Common, which adds War3Api.Common.dll to the libs_.
Part of this package is the following code:
```csharp
namespace War3Api
{
    public static partial class Common
    {
        /// @CSharpLua.Template = "FourCC({0})"
        public static extern int FourCC(string value);
    }
}
```

Now when I use this function, it should be compiled to "FourCC", but instead it becomes "War3Api.Common.FourCC", which does not exist.

Related: #264

Edit: Forgot I need to pass metas for this to work. I changed the code to add War3Api.Common.xml to metas_. However, it now throws an exception in XmlMetaProvider.DeserializeXmlMetaFile:

System.Exception: load xml file wrong at C:\Users\<user>\.nuget\packages\War3Api.Common\1.32.0.4-beta1\lib\netstandard1.0\War3Api.Common.xml ---> System.InvalidOperationException: There is an error in XML document (2, 2). ---> System.InvalidOperationException: <doc xmlns=''> was not expected.

The file looks like this:
```xml
<?xml version="1.0"?>
<doc>
    <assembly>
        <name>War3Api.Common</name>
    </assembly>
    <members>
        <member name="T:War3Api.Common">
            <summary>
            Contains all Warcraft III native functions.
            </summary>
        </member>
-- more members....
        <member name="M:War3Api.Common.FourCC(System.String)">
            @CSharpLua.Template = "FourCC({0})"
        </member>
    </members>
</doc>

**Comment by Drake53** [comment]
Update: I have implemented this in my fork, so I won't be needing help with this anymore. I'll leave the issue open in case you want to support this feature as well. My solution uses auto-generated classes for the <doc> xml model, which produce quite ugly code, so I won't be making a pull request.

**Comment by yanghuan** [comment]
doc commnet can not load from dll,  you can use xml to pass metdata like 
https://github.com/yanghuan/CSharp.lua/blob/master/CSharp.lua/System.xml
you can use -m cmd argumnet to add new xml metadata files.

**Comment by Drake53** [comment]
I realized I was doing it incorrectly after I submitted the issue, but after that there was another issue.
The .xml file with documentation has a different structure from your System.xml file:

System.xml:
```xml
<meta>
  <assembly>
    <namespace>
      <class>
...
```

Autogenerated documentation .xml file:
```xml
<doc>
  <assembly>
  </assembly>
  <members>
    <member>
...
```

**Comment by yanghuan** [comment]
Yes, the format is different.

**Comment by Drake53** [comment]
Do you have plans to support this format?

I think one of the nice things about this format would be that you can easily look up the documentation using symbol.GetDocumentationCommentId(). This returns a string that is the same in the <doc> file.
It is useful when symbol.GetDeclaringSyntaxNode() returns null, because symbol.IsFromAssembly() is true. [Example](https://github.com/Drake53/CSharp.lua/commit/9086b95520f51a56f75d93cdff62d2f362382561#diff-01dcf396bc4ea07692f3e2efeb95e7a3)

**Comment by yanghuan** [comment]
Thanks for your advice. but  this format is not designed to support metadata, so not plans to support this format.
