### ISSUE TITLE
Lua中System.typeof存在异常，使用typeof可以正常跨域调用

### ISSUE THREAD

**Issue by DukeChiang** [yanghuan/CSharp.lua#280]
重现代码：
Bridge/TestUtils.cs：

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using UnityEngine;
using UnityEditor;

[LuaAutoWrap]
public static class TestUtils
{
	public static GameObject Load(string path)
	{
		GameObject prefab = (GameObject)AssetDatabase.LoadMainAssetAtPath(path);
		CSharpLua.BaseUtility.Provider.ConvertCustomMonoBehaviour(ref prefab);
		return prefab;
	}

	public static Component Ensure(this GameObject gameObject, Type component)
	{
		if (gameObject && component != null && component.IsSubclassOf(typeof(Component)))
		{
			var t = gameObject.GetComponent(component);

			if (!t)
			{
				t = gameObject.AddComponent(component);
			}

			return t;
		}

		return null;
	}
}

Bridge/TestMonoBehaviour.cs：

using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[LuaAutoWrap]
public class TestMonoBehaviour : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}

Compiled/Sample/TestHelloWorld.cs:

		private void Start()
		{
                        //测试调用
			gameObject.Ensure(typeof(TestMonoBehaviour));
		}

异常结果：
LuaException: Compiled/Sample/TestHelloWord:85: bad argument #2 to 'Ensure' (Type expected, got table)
stack traceback:
	[C]: in function 'Ensure'
	Compiled/Sample/TestHelloWord:85: in function <Compiled/Sample/TestHelloWord:60>
LuaInterface.LuaDLL:luaL_argerror(IntPtr, Int32, String) (at Assets/ToLua/Core/LuaDLL.cs:699)
LuaInterface.LuaDLL:luaL_typerror(IntPtr, Int32, String, String) (at Assets/ToLua/Core/LuaDLL.cs:713)
LuaInterface.ToLua:CheckMonoType(IntPtr, Int32) (at Assets/ToLua/Core/ToLua.cs:1077)
TestUtilsWrap:Ensure(IntPtr) (at Assets/Source/Generate/TestUtilsWrap.cs:39)
LuaInterface.LuaDLL:lua_pcall(IntPtr, Int32, Int32, Int32)
LuaInterface.LuaState:PCall(Int32, Int32) (at Assets/ToLua/Core/LuaState.cs:765)
LuaInterface.LuaFunction:PCall() (at Assets/ToLua/Core/LuaFunction.cs:96)
LuaInterface.LuaFunction:Call(LuaTable) (at Assets/ToLua/Core/LuaFunction.cs:128)
CSharpLua.BridgeMonoBehaviour:Start() (at Assets/CSharpLua/CSharpLuaClient.cs:60)

期望结果：
TestMonoBehaviour组件被挂在到场景的Hello上

**Comment by yanghuan** [comment]
https://github.com/yanghuan/CSharp.lua/blob/master/CSharp.lua/CoreSystem.Lua/CoreSystem/Type.lua#L309

加了System.config.customTypeof, 可以通过这个处理下

**Comment by DukeChiang** [comment]
System.config.customTypeof = _G.typeof 这个意思吗

**Comment by yanghuan** [comment]
先判断是否是来自CSharp wrap的类型, 是的话使用_G.typeof
正好有一个函数isFromCSharp, 看下 Classloader.lua  里面有配置config的代码

**Comment by DukeChiang** [comment]
嗯，已经改过了
