### ISSUE TITLE
GetCustomAttributes方法获取的结果有错误，如果第一个参数是lua中的Atrribute返回值就把所有Attribute返回回来了

### ISSUE THREAD

**Issue by DukeChiang** [yanghuan/CSharp.lua#281]
重现代码：
Sample/TestAttribute.cs

public class TestAttribute : Attribute
	{
		public Type TestType { get; }

		public TestAttribute()
		{
			TestType = GetType();
		}
	}

Sample/Test.cs
[Test]
	[Bridge]
	public class Test
	{

	}

Bridge/BridgeAttribute.cs
using System;

[LuaAutoWrap]
public class BridgeAttribute : Attribute
{
	public Type Type { get; }

	public BridgeAttribute()
	{
		Type = GetType();
	}
}

Sample/TestHelloWorld.cs

		private void Start()
		{
			var test = new Test.Test();
			var objects = test.GetType().GetCustomAttributes(typeof(Test.TestAttribute), true);

			if(objects != null)
			{
				foreach(var item in objects)
				{
					var testAttribute = item as Test.TestAttribute;

					print("TestHelloWorld.Start:" + testAttribute);
				}
			}
		}

异常结果：
TestHelloWorld.Start:Sample.Test.TestAttribute
TestHelloWorld.Start:BridgeAttribute

期望结果：
TestHelloWorld.Start:Sample.Test.TestAttribute

**Comment by yanghuan** [comment]
https://github.com/yanghuan/CSharpLuaForUnity/blob/master/Assets/Lua/Classloader.lua#L14

这行改成 return false
