### ISSUE TITLE
Arrays?

### ISSUE THREAD

**Issue by brandonros** [yanghuan/CSharp.lua#285]
```
local System = System
local ArrayByte = System.Array(System.Byte)
local ArrayInt32 = System.Array(System.Int32)
local ArrayUInt32 = System.Array(System.UInt32)
```

Is this supposed to work?

**Comment by yanghuan** [comment]
yes, it can work. Is there a problem?

**Comment by brandonros** [comment]
```
$lua main.lua
lua: main.lua:3: attempt to index a nil value (local 'System')
stack traceback:
	main.lua:3: in main chunk
	[C]: in ?
```

https://www.tutorialspoint.com/execute_lua_online.php

**Comment by brandonros** [comment]
![image](https://user-images.githubusercontent.com/8949910/75199149-496abc80-5730-11ea-9b84-70dc2eb9013a.png)

**Comment by yanghuan** [comment]
you should load CoreSystem library first
https://github.com/yanghuan/CSharp.lua/tree/master/CSharp.lua/CoreSystem.Lua

there is a example
https://github.com/yanghuan/CSharp.lua/tree/master/test/fibonacci
