### ISSUE TITLE
Syntactic sugar for `params` not respected

### ISSUE THREAD

**Issue by timothywalter** [yanghuan/CSharp.lua#29]
Having a method with params like so:
C#: `[...] public void Log(object thing, params object[] args)`
And calling it like:
C#: `[...] Log("Testing something {0}:", 1234);`
Generates:
Lua: `[...] Log("Testing something {0}:", 1234)`
When it should generate:
Lua: `[...] Log("Testing something {0}:", System.Array(System.Object)(1234))`

The syntactic sugar normally applied by the compiler (turning params arguments into an array) is missing and therefor valid C# code will compile to incorrect Lua code.

Workaround is to not use params or just pass an array yourself.

**Comment by yanghuan** [comment]
write
```
using System;

namespace HelloLua {
    public static class Program {
        public static void Main() {
          Log("Testing something {0}:", 1234);
        }

       public static void Log(object thing, params object[] args) {
       }
    }
}
```
will be 
```
-- Generated by CSharp.lua Compiler 1.1.0
local System = System
System.namespace("HelloLua", function (namespace) 
  namespace.class("Program", function (namespace) 
    local Main, Log
    Main = function () 
      Log("Testing something {0}:", System.Array(System.Object)(1234))
    end
    Log = function (thing, args) 
    end
    return {
      Main = Main, 
      Log = Log
    }
  end)
end)
```
 params arguments  will be wrap to array, at call point. it is very correct i think...,  I'm not very clear about your. can you give more information？

**Comment by timothywalter** [comment]
Yes correct, I am sorry I now see this is only happening when the method is in another assembly.

Write in TestLibrary.csproj:
```namespace TestLibrary
{
    public class Console
    {
        public static void Log(object thing, params object[] args)
        {
            // Do something with args
        }
    }
}```

Write in HelloLua.csproj:
```namespace HelloLua
{
    class Program
    {
        static void Main(string[] args)
        {
            TestLibrary.Console.Log("Testing something {0}:", 1234);
        }
    }
}
```

Add Reference to TestLibrary in HelloLua and compile with:
```
dotnet "%dir%CSharp.lua.dll" -c -s ./TestLibrary/ -d output/TestLibrary -l %lib%Microsoft.CodeAnalysis.CSharp.dll;%lib%Microsoft.CodeAnalysis.dll
dotnet "%dir%CSharp.lua.dll" -c -s ./HelloLua/ -d output/HelloLua -l %lib%Microsoft.CodeAnalysis.CSharp.dll;%lib%Microsoft.CodeAnalysis.dll;./TestLibrary/bin/Debug/netstandard2.0/TestLibrary.dll
```

**Comment by yanghuan** [comment]
#30
