### ISSUE TITLE
用静态变量赋值给成员变量时，会报错

### ISSUE THREAD

**Issue by mybios** [yanghuan/CSharp.lua#3]
using System;
namespace UnitTest
{

    public class StaticClassA
    {
        public static StaticClassA field1 = new StaticClassA();
    }

    public class StaticClassB
    {
        StaticClassA field2 = StaticClassA.field1;
        static StaticClassA field3 = StaticClassA.field1;
        StaticClassB()
        {
            StaticClassA field4 = StaticClassA.field1;
        }

    }

}

用这个测试用例，转换时会报错，望修复。

**Comment by yanghuan** [comment]
多谢提供用例，已经修正
https://github.com/yanghuan/CSharp.lua/commit/ac1532a820785103d396ba676f3c1ce8d4a19d32
