### ISSUE TITLE
Lua error() and table as parameter 

### ISSUE THREAD

**Issue by Vbif** [yanghuan/CSharp.lua#309]
I have run to some issue with exceptions. All of them print as "(null)(null)" in my "enviroment" . I have tried to read the docs and checked some online lua compiler and it looks like error() only accept string as first parameter, not table.
Is it really correct to pass table to error()?
https://github.com/yanghuan/CSharp.lua/blob/master/CSharp.lua/CoreSystem.Lua/CoreSystem/Core.lua#L62

**Comment by yanghuan** [comment]
You need to use a higher version of the lua environment，like luajit or lua 5.2+

**Comment by Vbif** [comment]
Oh, I did not know this, thanks for clarification. Is there some other things that can be broken on lua 5.1?

**Comment by yanghuan** [comment]
you can change  " error(e)" to " error(tostring(e))"   , but It will cause an exception to fail to catch
