### ISSUE TITLE
Non natively supported system assemblies.

### ISSUE THREAD

**Issue by VistianOpenSource** [yanghuan/CSharp.lua#313]
I've been using your library for awhile with relatively simple conversions of C# code to Lua.

Now however I have a requirement to try and use the HttpClient class to download some content from a remote site.

Whilst this code 

```
using System;
using System.Net.Http;
using System.Threading.Tasks;

namespace SimpleHttp
{
    class Program
    {
        private const string URL = "https://www.google.com";

        static readonly HttpClient client = new HttpClient();

        static async Task Main(string[] args)
        {
            var response = await client.GetAsync("http://www.google.com/");

            response.EnsureSuccessStatusCode();

            var body = await response.Content.ReadAsStringAsync();

            Console.WriteLine("Hello World! "+body);

            return;
        }
    }
}
```
does compile into Lua as:
```
-- Generated by CSharp.lua Compiler
local System = System
local SystemNetHttp = System.Net.Http
System.namespace("SimpleHttp", function (namespace)
  namespace.class("Program", function (namespace)
    local URL, client, Main, static
    static = function (this)
      client = SystemNetHttp.HttpClient()
    end
    URL = "https://www.google.com"
    Main = function (args)
      return System.async(function (async, args)
        local response = async:await(client:GetAsync("http://www.google.com/"))

        response:EnsureSuccessStatusCode()

        local body = async:await(response:getContent():ReadAsStringAsync())

        System.Console.WriteLine("Hello World! " .. body)

      end, nil, args)
    end
    return {
      static = static
    }
  end)
end)
```
when i try to use it with the Lua command line I get a 

C:\Users\jamie\source\repos\yanghuan\CSharp.lua\test\__bin\lua5.1\lua: .\program.lua:3: attempt to index field 'Net' (a nil value)
stack traceback:
        .\program.lua:3: in main chunk
        [C]: in function 'require'
        C:\temp\csharplua\CoreSystem\Core.lua:1445: in function <C:\temp\csharplua\CoreSystem\Core.lua:1440>
        (tail call): ?
        laucher.lua:4: in main chunk
        [C]: ?

Now, I appreciate that only a small subset of the .net libraries have been converted but is there some way that the usage of HttpClient is "bridged" to the native assembly? I've used some Lua implementations on mobile whereby classes can be exposed to the Lua VM and I was wondering if there is something obvious/similar that I'm missing here ?

**Comment by yanghuan** [comment]
At the moment you need to adapt yourself to this class. Here's a similar implementation
https://github.com/mta-slipe/CSharp.lua/tree/development/CSharp.lua/CoreSystem.Lua/CoreSystem/Net/Http
