### ISSUE TITLE
Tasks support

### ISSUE THREAD

**Issue by VistianOpenSource** [yanghuan/CSharp.lua#314]
I may well be missing something here but I'm trying to understand how Tasks should function. I appreciate that Lua has Coroutines but, there would appear to be some async / await / tasks supported with CSharp.lua.

For example, if I try this code 

```
   class Program
    {
        static void  Main(string[] args)
        {
            var x = DoDelay();

            Console.WriteLine("Wait for greater than a second, you should see a 'Delay Done' message");

            Console.ReadLine();

            Console.WriteLine("DoDelay Task Status "+x.Status);
        }

        public static async Task DoDelay()
        {
            await Task.Delay(1000);

            Console.WriteLine("Delay Done");

            return;
        }
    }
```

When I run the C#, I do get the Delay Done message after a second and the task is indicated as RanToCompletion, but when I run it through CSharp.lua I see no Delay Done message, and the task status is WaitingForActivation.

So, the question is... what am I missing? 

Also given the usage of Tasks how should one await the outcome in Main? I've tried getting the result of the DoDelay task, but I then get an exception saying "mainThread not support" which I'm taking to mean that I can't await the result.

Once again, thanks again for any feedback pointers.

**Comment by yanghuan** [comment]
In C#,  Task.Delay(1000) run in another thread, when Console.ReadLine() block main thread, will change the task's status, but in lua, just one thread, can not do this.

if you use task and timer, you should inset config code when load coreSystem.lua
for example
https://github.com/yanghuan/CSharpLuaForUnity/blob/master/Assets/Lua/Classloader.lua#L17&L57

**Comment by VistianOpenSource** [comment]
Thanks for the response.

What I'm looking to try and do is utilize 'Lua' as part of a mobile application. Currently there is an interface in a mobile app which has a method which returns a Task. The existing implementations of this interface are all written in C# so these are easy to implement.

To allow for customization / additional functionality however I would like to be able to provide a "Wrapper class" for this interface for which the actual implementation of the method which returns a task is written in Lua. So i'm looking at how viable this can be.  side note - sometimes these implementations would be performing http requests (I've looked at the http client implementation you pointed me at the other day and I believe that all i have to implement is a fetch method - in this case i'm assuming it would be C# code).

Coming back to CSharp.lua, what I would to achieve is that the implementations of this interfaces method which is a Task is written in C#, this is then converted to Lua using your library and this Lua is then consumed by the mobile app.

But currently I'm struggling at the 'bridging' between C# task world and Lua. I'm using NLua so I have access to C# methods etc, but as far as I understand it, whilst the call into the Lua doesn't necessarily have to be blocking, some callback mechanism would be required for the lua code to indicate when it has completed.

Do you have insights suggestions as to how this might be achieved using your library?

**Comment by yanghuan** [comment]
You can implement the interface as a callback, so that both Lua and C# are the same and easy to use.

**Comment by VistianOpenSource** [comment]
Thanks, I suspect what I may 'try', given I know the host environment for Lua, is look to swap out some of the implementation for tasks / threads in the Lua to make calls into C# implementations instead.  Going to go and experiment...
