### ISSUE TITLE
Generic Extension generation conventions

### ISSUE THREAD

**Issue by VistianOpenSource** [yanghuan/CSharp.lua#316]
This isn't an issue report per se, but rather more a "why" question.

I'm currently looking to use CSharp.lua to take C# to generate Lua but with some of the code being external to Lua and the Lua calls out to it. I've been achieving this with NLua, but I have a question about why something is implemented in a certain way.

For example, if I have a generic class e.g.

``public class AndroidView<TView>``

then I get generated Lua of the form:

``local AndroidView_1EditText = BirchViews.AndroidView_1(AndroidWidget.EditText)``

We construct the instances through extension methods and when the class is constructed, this is correct translated to 

``BirchViews.Primitives.EditText()``

So far, all good, note that AndroidView_1EditText isn't used for the construction BUT.... we have many generic extension methods of the form

``public static TControl InputType<TControl>(this TControl control, int inputType) where TControl:IReflectedPrimitive<Android.Widget.EditText>``

which are used to apply additional attributes, in effect the developer daisy chains these together.

When these are translated through CSharpLua however, the 

original C# code

``password.InputType(InputTypes.ClassText | InputTypes.TextVariationPassword);``

gets translated to

``BirchViews.Android_Widget_TextView_Extensions.InputType(password, 129 --[[InputTypes.ClassText | InputTypes.TextVariationPassword]], AndroidView_1EditText)``

So my question(s) is/are:

1. Why is the type for the generic extension method the last parameter and not say the 1st?
2. Would it make sense for generic extension methods to follow the convention you have for generic types to be of the same form, e.g. _<<number of generic parameters>>(generic parameter type 1,generic parameter type 2...) so the above would instead become

``BirchViews.Android_Widget_TextView_Extensions.InputType_1(AndroidView_1EditText,password, 129 --[[InputTypes.ClassText | InputTypes.TextVariationPassword]])``

**Comment by yanghuan** [comment]
some times, the generic parameter can be ignore. like linq.Where
at last it can do this
