### ISSUE TITLE
Question: Usage of -module and -l parameter

### ISSUE THREAD

**Issue by br0esel** [yanghuan/CSharp.lua#318]
As an example I have a library
```csharp
using System;

namespace Library
{
    public class Class1
    {
        public  void Nope()
        {
             Console.WriteLine("Lib");
        }
    }
}
```
And a console app which uses this library
```csharp
using Library;
using System;

namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            Class1 temp = new Class1();
            temp.Nope();
        }
    }
}
```
As far as I understand I have to compile the library with the -module parameter and reference it in the consoleApp with the -l paramter and add a !after the modulename.
So i tried:
```cmd
CSharp.lua.Launcher -s Class1.cs -d out/lib -module
CSharp.lua.Launcher -s Program.cs -d out/app -l out/lib!
```
But i get a "-l C:\Users\................\lib.dll is not found"
Executing the compiler with or wihout -module parameter makes no difference. The output are the exact same Class1.lua and manifest.lua files.
The error message confuses me. Should the compiler generate a .dll file for the module? Or do I reference the module incorrectly in the second step?

**Comment by yanghuan** [comment]
you can check the work directory, the lib is  search  at work directory,

**Comment by br0esel** [comment]
The problem is there is no .dll file when i use the lua-compiler with the "-module" parameter. The outputs are always .lua files + manifest.lua. 
So how's this gonna work when "-l" expects a .dll file as input parameter.

**Comment by yanghuan** [comment]
.dll is build by C# compiler
