### ISSUE TITLE
Any supported DI containers

### ISSUE THREAD

**Issue by flynicodrive** [yanghuan/CSharp.lua#325]
What dependency container may be used in this project? I try to use TinyIoC, but some methods not implemented: type ContainerInfo, Type.IsAbstract, may be some else.

**Comment by yanghuan** [comment]
what is ContainerInfo ?

**Comment by flynicodrive** [comment]
Sorry i was sleepy, ConstructorInfo. I need to inject constructor.

**Comment by flynicodrive** [comment]
-metadata       : export all metadata, use @CSharpLua.Metadata annotations for precise control
Find this, try to use
