### ISSUE TITLE
'os' undefined

### ISSUE THREAD

**Issue by thisbarker** [yanghuan/CSharp.lua#329]
When building a simple application using -include '...' it throws an error on references to 'os'

CoreSystemLib: DateTime.lua
os
os.time
os.difftime
os.date

CoreSystemLib: IO/File.lua
os.remove

CoreSystemLib: Random.lua
os.time

CoreSystemLib: Utilities.lua
os
os.clock
os.exit

**Comment by yanghuan** [comment]
you environment is not has os table, maybe you should implementation it

**Comment by thisbarker** [comment]
Is the `os` table suppose to be part of the LUA base? I am using Lua 5.1.

**Comment by yanghuan** [comment]
std lua 5.1 has os table
