### ISSUE TITLE
Calling native C functions bound in Lua

### ISSUE THREAD

**Issue by MDLeide** [yanghuan/CSharp.lua#33]
I'm having trouble understanding how I can call C-functions that were bound to Lua when it is being used to script another program. For instance, `Class Foo`, writing in C, has method` Foo.Do()` which returns a `Bar`. It binds `Foo.Do()` to Lua, exposing it as` you.do().` So then, in Lua, I can do something like this, even though `you.do()` is never declare in the Lua files:

```
Function Work()
    local result = you.do()
end
```

In C#, though, you.do() is not defined. I could write some mocks with interfaces and statics, where the body just throws an exception. I'm not sure if that will cause problems with your library though?

Just FYI, I have no control over the application declaring `Foo.Do()`.

What's the best way to achieve this? 

Thank you.

**Comment by yanghuan** [comment]
you can use a empty dll provide interface
The way you're currently using is already available.

**Comment by MDLeide** [comment]
So when I 'compile' to Lua I'm not going to be raising exceptions all over? I know I can just try this out, I just wanted to make sure this library was viable for my purpose before investing. Thank you.

**Comment by MDLeide** [comment]
Is there any way to instruct all output to be given to a single file? That is part of my current requirement.

**Comment by yanghuan** [comment]
lua module system exists, decentralized to different files easier to manage, does not currently support the merger to a file

lua local variables can not seem to be greater than the number of 256, merged into a document, there may be problems

**Comment by MDLeide** [comment]
Yeah, unfortunately for the project I am working on, they only accept a single file, concatenated into their options file. Oh well, still a great utility. Thank you.
