### ISSUE TITLE
BUG: Interface/generic type retrieval

### ISSUE THREAD

**Issue by Orden4** [yanghuan/CSharp.lua#349]
Sample:

```csharp
using System;
using System.Reflection;
using System.Collections.Generic;
using System.Linq;

namespace LuaTest {
  public class Program {
	private static void Main(string[] args)
	{
		var test = new MyTestClass<int>();
		var types = test.GetType().GetInterfaces()
			.Where(x => x.IsGenericType)
			.Select(x => x.GetGenericTypeDefinition())
			.ToList();
		
		Console.WriteLine(typeof(IMyInterface<>).FullName);
		Console.WriteLine(types.Contains(typeof(IMyInterface<>)));
		Console.WriteLine(types.Count);
	}
  }
  
  public interface IMyInterface<T>
  { }
  
  public class MyTestClass<T> : IMyInterface<T>
  { }
}
```

This will fail because of a bug in GetGenericTypeDefinition. The fix to this seems to be changing the implementation of GetGenericTypeDefinition in Type.lua to:

```lua
  GetGenericTypeDefinition = function (this)
    if isGenericTypeDefinition(this) then
      return this
    end
    local name = this[1].__name__
    local i = name:find('%[')
    if i then
      local genericTypeName = name:sub(1, i - 1):gsub('`', '_')
      return typeof(System.getClass(genericTypeName))
    end
    throw(System.InvalidOperationException())
  end
```

However, there is more going wrong. It seems that both `typeof(IMyInterface<>)` and `GetGenericTypeDefinition()` are resolving to `System.Object` instead of  `LuaTest.IMyInterface`.  
I don't really understand enough about the type definitions to figure out why this is happening.

**Comment by Orden4** [comment]
Thanks for the fix. My own issue is resolved with these fixes, since all I wanted was for equalities to work correctly, which they now do. However, it seems that `typeof(IMyInterface<>).FullName` is still outputting `System.Object`. This isn't a problem for me, but I figured I should inform you.

**Comment by yanghuan** [comment]
Thank you for your feedback, I also found this problem, I will try to fix it
