### ISSUE TITLE
Build for .NET Standard 2.0 to allow reuse of this as a library?

### ISSUE THREAD

**Issue by soccermitchy** [yanghuan/CSharp.lua#35]
Hey, I wrote a [Cake](https://cakebuild.net) addin for CSharp.Lua to allow building projects with it. One of the modifications I had to make to allow this though was rebuilding the project with .NET Standard 2.0 instead of as a .net core application. Would it be possible to split the actual compiler off into a library and have the console application separate? I could probably submit a PR for this if needed, but I wanted to know if I was the only one who needed that.

Btw, if anyone wants access to it, I have an example project using my Cake module here: https://git.nofla.me/cgit/rtech/cake-csharp.lua-example (I don't use Github anymore for my personal projects)

**Comment by yanghuan** [comment]
I am honored that CSharp.lua can bring you some help.
This project is a console project, but you can aslo reference as a dll, the class named "CSharpLua.Worker" is public, you can use it directly. Is that ok ?

**Comment by soccermitchy** [comment]
Yes, that's what I'm doing right now, but it would make it easier to work with if it used `netstandard2.0` instead of `netcoreapp2.0` in the .csproj since then I wouldn't need to recompile this to use it.
