### ISSUE TITLE
BUG: Generic class extension+property within own namespace

### ISSUE THREAD

**Issue by Orden4** [yanghuan/CSharp.lua#351]
I was thinking of just ignoring this one since it's some pretty convoluted combination of generic usage, but after I looked into it some more I thought a solution probably isn't too hard, but I'm still having trouble wrapping my head around the AST parsing. Plus, I thought up two different solutions to the problem, but am not really sure which is best.

Sample:
```csharp
using System;
using System.Reflection;
using System.Collections.Generic;
using System.Linq;

namespace LuaTest {
	public class Program {
		private static void Main(string[] args)
		{
			var a = new ExtendedClass();
			Console.WriteLine(a.Property.Value);
		}
	}
	
	public class BaseClass<T>
	{
		public Test<T> Property { get; set; } = new Test<T>();
	}
	public class ExtendedClass : BaseClass<int> { }
	public class Test<T>
	{
		public T Value { get; set; }
	}
}
```

This results in the following error (single file mode):
```
lua53.exe: out.lua:17592: attempt to index a nil value (upvalue 'LuaTest')
stack traceback:
        out.lua:17592: in upvalue 'cls'
        out.lua:348: in field 'BaseClass_1'
        out.lua:17613: in local 'extends'
        out.lua:196: in upvalue 'applyExtends'
        out.lua:221: in upvalue 'setBase'
        out.lua:306: in function <out.lua:297>
        (...tail calls...)
        out.lua:1549: in field 'init'
        out.lua:17645: in main chunk
        [C]: in ?
```

What's happening here is that the `base` of `ExtendedClass` is causing `BaseClass_1` to be invoked, which in turn tries to do `local Test_1T = LuaTest.Test_1(T)` which fails, since `LuaTest` has not yet been imported/instantiated. Trying this with e.g. `List<T>` instead of `Test<T>` works fine, because System is already fully defined.

The easy fix to this problem seems to be to just move the instantiation of `Test_1T` to the constructor, but I don't know if that won't cause other problems (maybe in the case of multiple constructors and/or Activator.CreateInstance?).
Alternatively, `base` shouldn't be called until after the imports have been completed, but this may also require reorganising to ensure that `Test_1` is defined before `ExtendedClass`.
These were the solutions I came up with, but perhaps you have a better solution.

**Comment by Orden4** [comment]
Sorry for my persistence, but I'm just not really sure if we're having a miscommunication issue here or if you're just not interested in fixing this rather specific interaction. As said in the pull request, https://github.com/yanghuan/CSharp.lua/commit/051844264c3e7a65b751e355d4f7595ec83ff3b4 does not address the issue to my knowledge, as moving the type initialisation of `Test_1` to an earlier point in the list is insufficient due to `LuaTest` being referenced before the the imports have been resolved.

I understand at least that you don't want to handle generic type resolution in the constructor, which I can understand because it is indeed less than ideal from a performance perspective to always do it the hard way for this rare scenario. Still, I would like it if this scenario didn't cause problems... I will try and see if I can create a better pull request somewhere during the next few days that doesn't require additional type resolution after initialization.

**Comment by yanghuan** [comment]
I am sorry, i not found this problem
