### ISSUE TITLE
"Attempt to index a nil value" error with arrays

### ISSUE THREAD

**Issue by WattanaGaming** [yanghuan/CSharp.lua#353]
I was testing out CSharp.Lua and making a dummy class for OpenComputers functions but it seem to have problem with arrays. This is what the error says: 
![image](https://user-images.githubusercontent.com/25323231/112142471-395e2e80-8c09-11eb-805a-63578c4d80f8.png)

I then decided to also test the codes on Replit and I got the exact same error:
```
lua: ./Core/CoreSystem/Core.lua:406: attempt to index local 'T' (a nil value)
stack traceback:
    ./Core/CoreSystem/Core.lua:406: in function <./Core/CoreSystem/Core.lua:403>
    (tail call): ?
    ./build/OpenComputers/computer.lua:4: in main chunk
    [C]: in function 'require'
    ./Core/CoreSystem/Core.lua:1552: in function <./Core/CoreSystem/Core.lua:1547>
    (tail call): ?
    [string "<eval>"]:2: in main chunk
```

The source code and the compiled files are hosted here: https://replit.com/join/icjughnc-wattanagaming. Note that the CoreSystem libraries which are commented out are also causing errors.

**Comment by yanghuan** [comment]
https://replit.com/@WattanaGaming/CSharplua-error#Core/All.lua
line 27 should open

**Comment by WattanaGaming** [comment]
Hmm, this is kind of weird to me. I guess the problem with the string library is caused by OC itself.
