### ISSUE TITLE
CoreSystem需要支持SortedDictionary

### ISSUE THREAD

**Issue by zxt385189207** [yanghuan/CSharp.lua#357]
SortedDictionary 用到的地方例如ET中的 TimerComponent 设计，还有一些 Actor 设计也用到这个。
![4QP$XZ%~ZPG%E0L5{%)4@ES](https://user-images.githubusercontent.com/20718536/116648727-50cecb00-a9b0-11eb-8dd0-2c167ef5befa.jpg)

**Comment by leafsnow** [comment]
自己写一个低效率版本的应该不难，用一个table当作Dictionary，然后另外一个table记录keys，迭代的时候，就给keys的table排序一次，遍历排序的keys取值。 😅

**Comment by yanghuan** [comment]
fix by 6b9b70155a386bd872ee78b7858e2d524708b3e4
