### ISSUE TITLE
Can not run the resulting Lua code

### ISSUE THREAD

**Issue by mingodad** [yanghuan/CSharp.lua#359]
I'm trying to test the resulting Lua code from the online converted `fibonacci` (see bellow) and I'm getting the error shown bellow, it's not clear in the documentation how to execute the converted programs, where the namespaces/classes can be found ?

Cheers !
```
lua "fibonacci.lua"
lua: fibonacci.lua:46: attempt to index a nil value (global 'Test')
stack traceback:
	fibonacci.lua:46: in main chunk
	[C]: in ?
```

```
require("All")()

-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Test", function (namespace)
  namespace.class("Program", function (namespace)
    local Main, FibonacciN, FibonacciSequence
    Main = function (args)
      System.Console.WriteLine("Print Fibonacci sequence")
      System.Console.WriteLine("Input n:")
      local num = System.Console.ReadLine()
      local count
      local default
      default, count = System.Int32.TryParse(num, nil)
      if not default then
        System.throw(System.ArgumentException(num .. " is unlawful"))
      end
      local sequence = FibonacciSequence(count)
      for _, v in System.each(sequence) do
        System.Console.Write(v)
        System.Console.WriteChar(44 --[[',']])
      end
    end
    FibonacciN = function (n)
      if n == 0 then
        return 0
      elseif n == 1 then
        return 1
      else
        return FibonacciN(n - 1) + FibonacciN(n - 2)
      end
    end
    FibonacciSequence = function (n)
      return System.yieldIEnumerable(function (n)
        for i = 0, n - 1 do
          System.yield(FibonacciN(i))
        end
      end, System.Int32, n)
    end
    return {
      Main = Main
    }
  end)
end)

Test.Program.Main()
--System.namespace.Test.Program.Main()
--for k,v in pairs(_G) do print(k,v) end
--for k,v in pairs(System) do print(k,v) end
```

**Comment by yanghuan** [comment]
you can see this sample
https://github.com/yanghuan/CSharp.lua/tree/master/test/fibonacci

**Comment by mingodad** [comment]
I saw that example but it assumes we are running on windows and it also assume some file/module called `out.manifest` that the online demo do not generate/show.

I'm running on Linux and want to execute the generated Lua using the lua `CoreSytem`, is it possible ?

**Comment by mingodad** [comment]
Here is the HelloLua form the README with the missing pieces, how to run it ?
```
require("All")()

-- Generated by CSharp.lua Compiler
local System = System
System.namespace("HelloLua", function (namespace)
  namespace.class("Program", function (namespace)
    local Main
    Main = function ()
      System.Console.WriteLine("hello lua!")
    end
    return {
      Main = Main
    }
  end)
end)

HelloLua.Program.Main()
```
Output:
```
lua "hello-cs.lua"
lua: hello-cs.lua:17: attempt to index a nil value (global 'HelloLua')
stack traceback:
	hello-cs.lua:17: in main chunk
	[C]: in ?
```

**Comment by mingodad** [comment]
I'm trying to get CocoR parser generator from https://ssw.jku.at/Research/Projects/Coco/ to work in Lua using your project, I concatenated everything in one file and using the online tool https://yanghuan.github.io/external/bridgelua-editor/index.html I got a resulting code (see attached) that I'm wiling to test but I could not find how.
[Coco-lua.zip](https://github.com/yanghuan/CSharp.lua/files/6521486/Coco-lua.zip)

**Comment by mingodad** [comment]
Rereading the docs they mention the generation of `Manifest.lua` but the online tool do not **show/generate** it.

**Comment by yanghuan** [comment]
download

**Comment by yanghuan** [comment]
download 
https://github.com/yanghuan/CSharp.lua/releases/download/1.7/CSharp.lua-1.7.zip
use the command 
https://github.com/yanghuan/CSharp.lua#command-line-parameters

**Comment by yanghuan** [comment]
the online tool  is only show the output lua code

**Comment by mingodad** [comment]
Could you give the manifest file for the `HelloLua` so that I can deduce/understand what's the missing pieces are ?

I do not have a windows machine at hand and I'm OK using only the online tool for testing right now !

Cheers !

**Comment by yanghuan** [comment]
net 5 is cross platform
https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-5.0.6-linux-x64-binaries

**Comment by mingodad** [comment]
This is what I was expecting as answer and think that is a good idea to have on the README:
```
require("All")()

-- Generated by CSharp.lua Compiler
local System = System
System.namespace("HelloLua", function (namespace)
  namespace.class("Program", function (namespace)
    local Main
    Main = function ()
      System.Console.WriteLine("hello lua!")
    end
    return {
      Main = Main
    }
  end)
end)

-- This is the main function of the generated manifest
System.init({
    --path = path,
    --files = {
    --  "Program"
    --},
    types = {
      "HelloLua.Program"
    },
    Main = "HelloLua.Program.Main"
  })

  HelloLua.Program.Main()
```
Cheers !
