### ISSUE TITLE
Argument mismatch on littleEndian

### ISSUE THREAD

**Issue by quinchs** [yanghuan/CSharp.lua#361]
# Summary
When compiling my code for some testing with [Computercraft Tweaked](https://tweaked.cc/) minecraft mod, I had a few issues with the source file generated

### Arguments
```
dotnet .\CSharp.lua.Launcher.dll -s "sourceDir" -d "destDir" -include "..\CSharp.lua-1.7\CoreSystem.lua"
```

### Issue
After getting some errors trying to run the `out.lua` file, i noticed that this code fails
```lua
-- https://github.com/ToxicFrog/vstruct/blob/master/io/endianness.lua#L30
local isLittleEndian = true
if rawget(global, "jit") then
  if require("ffi").abi("be") then
    isLittleEndian = false
  end
else 
  local dump = string.dump
  if dump and sbyte(dump(System.emptyFn, 7)) == 0x00 then
    isLittleEndian = false
  end
end
```

After looking at the included github link i noticed that the dump parameter has a mismatch in it
```lua
-- original
sbyte(dump(System.emptyFn, 7))

-- linked
string.byte(string.dump(function() end), 7)
```
after changing the if statement to the linked one
```lua
sbyte(dump(System.emptyFn), 7)
```
it fixed the issue. I don't know if this is just the version of lua running in the mod (5.2) or if its just a simple type.

**Comment by yanghuan** [comment]
thank very mush, i will fix
