### ISSUE TITLE
还是60 闭包问题。  

### ISSUE THREAD

**Issue by kkvskkkk** [yanghuan/CSharp.lua#377]
using System;
using System.Collections.Generic;

namespace HelloLua {
	public static partial class Program {
		 public static void Main(string[] args) 
		 {
			 Console.WriteLine("haha");
		 }
		 
		 private static List<int> L1 = new List<int>();
		 private static List<int> L2 = new List<int>();
		 private static List<int> L3 = new List<int>();
		 private static List<int> L4 = new List<int>();
		
		
		public static void Func0() { Console.WriteLine("hehe");}
		public static void Func1() { Console.WriteLine("hehe");}
		public static void Func2() { Console.WriteLine("hehe");}
		public static void Func3() { Console.WriteLine("hehe");}
		public static void Func4() { Console.WriteLine("hehe");}
		public static void Func5() { Console.WriteLine("hehe");}
		public static void Func6() { Console.WriteLine("hehe");}
		public static void Func7() { Console.WriteLine("hehe");}
		public static void Func8() { Console.WriteLine("hehe");}
		public static void Func9() { Console.WriteLine("hehe");}
		public static void Func10() { Console.WriteLine("hehe");}
		public static void Func11() { Console.WriteLine("hehe");}
		public static void Func12() { Console.WriteLine("hehe");}
		public static void Func13() { Console.WriteLine("hehe");}
		public static void Func14() { Console.WriteLine("hehe");}
		public static void Func15() { Console.WriteLine("hehe");}
		public static void Func16() { Console.WriteLine("hehe");}
		public static void Func17() { Console.WriteLine("hehe");}
		public static void Func18() { Console.WriteLine("hehe");}
		public static void Func19() { Console.WriteLine("hehe");}
		public static void Func20() { Console.WriteLine("hehe");}
		public static void Func21() { Console.WriteLine("hehe");}
		public static void Func22() { Console.WriteLine("hehe");}
		public static void Func23() { Console.WriteLine("hehe");}
		public static void Func24() { Console.WriteLine("hehe");}
		public static void Func25() { Console.WriteLine("hehe");}
		public static void Func26() { Console.WriteLine("hehe");}
		public static void Func27() { Console.WriteLine("hehe");}
		public static void Func28() { Console.WriteLine("hehe");}
		public static void Func29() { Console.WriteLine("hehe");}
		public static void Func30() { Console.WriteLine("hehe");}
		public static void Func31() { Console.WriteLine("hehe");}
		public static void Func32() { Console.WriteLine("hehe");}
		public static void Func33() { Console.WriteLine("hehe");}
		public static void Func34() { Console.WriteLine("hehe");}
		public static void Func35() { Console.WriteLine("hehe");}
		public static void Func36() { Console.WriteLine("hehe");}
		public static void Func37() { Console.WriteLine("hehe");}
		public static void Func38() { Console.WriteLine("hehe");}
		public static void Func39() { Console.WriteLine("hehe");}
		public static void Func40() { Console.WriteLine("hehe");}
		public static void Func41() { Console.WriteLine("hehe");}
		public static void Func42() { Console.WriteLine("hehe");}
		public static void Func43() { Console.WriteLine("hehe");}
		public static void Func44() { Console.WriteLine("hehe");}
		public static void Func45() { Console.WriteLine("hehe");}
		public static void Func46() { Console.WriteLine("hehe");}
		public static void Func47() { Console.WriteLine("hehe");}
		public static void Func48() { Console.WriteLine("hehe");}
		public static void Func49() { Console.WriteLine("hehe");}
		public static void Func50() { Console.WriteLine("hehe");}
		public static void Func51() { Console.WriteLine("hehe");}
		public static void Func52() { Console.WriteLine("hehe");}
		public static void Func53() { Console.WriteLine("hehe");}
		public static void Func54() { Console.WriteLine("hehe");}
		public static void Func55() { Console.WriteLine("hehe");}
		public static void Func56() { Console.WriteLine("hehe");}
		public static void Func57() { Console.WriteLine("hehe");}
		public static void Func58() { Console.WriteLine("hehe");}
		public static void Func59() { Console.WriteLine("hehe");}
		public static void Func60() { Console.WriteLine("hehe");}
		public static void Func61() { Console.WriteLine("hehe");}
		public static void Func62() { Console.WriteLine("hehe");}
		public static void Func63() { Console.WriteLine("hehe");}
		public static void Func64() { Console.WriteLine("hehe");}
		public static void Func65() { Console.WriteLine("hehe");}
		public static void Func66() { Console.WriteLine("hehe");}
		public static void Func67() { Console.WriteLine("hehe");}
		public static void Func68() { Console.WriteLine("hehe");}
		public static void Func69() { Console.WriteLine("hehe");}
		public static void Func70() { Console.WriteLine("hehe");}
		public static void Func71() { Console.WriteLine("hehe");}
		public static void Func72() { Console.WriteLine("hehe");}
		public static void Func73() { Console.WriteLine("hehe");}
		public static void Func74() { Console.WriteLine("hehe");}
		public static void Func75() { Console.WriteLine("hehe");}
		public static void Func76() { Console.WriteLine("hehe");}
		public static void Func77() { Console.WriteLine("hehe");}
		public static void Func78() { Console.WriteLine("hehe");}
		public static void Func79() { Console.WriteLine("hehe");}
		public static void Func80() { Console.WriteLine("hehe");}
		public static void Func81() { Console.WriteLine("hehe");}
		public static void Func82() { Console.WriteLine("hehe");}
		public static void Func83() { Console.WriteLine("hehe");}
		public static void Func84() { Console.WriteLine("hehe");}
		public static void Func85() { Console.WriteLine("hehe");}
		public static void Func86() { Console.WriteLine("hehe");}
		public static void Func87() { Console.WriteLine("hehe");}
		public static void Func88() { Console.WriteLine("hehe");}
		public static void Func89() { Console.WriteLine("hehe");}
		public static void Func90() { Console.WriteLine("hehe");}
		public static void Func91() { Console.WriteLine("hehe");}
		public static void Func92() { Console.WriteLine("hehe");}
		public static void Func93() { Console.WriteLine("hehe");}
		public static void Func94() { Console.WriteLine("hehe");}
		public static void Func95() { Console.WriteLine("hehe");}
		public static void Func96() { Console.WriteLine("hehe");}
		public static void Func97() { Console.WriteLine("hehe");}
		public static void Func98() { Console.WriteLine("hehe");}
		public static void Func99() { Console.WriteLine("hehe");}
		public static void Func100() { Console.WriteLine("hehe");}
		public static void Func101() { Console.WriteLine("hehe");}
		public static void Func102() { Console.WriteLine("hehe");}
		public static void Func103() { Console.WriteLine("hehe");}
		public static void Func104() { Console.WriteLine("hehe");}
		public static void Func105() { Console.WriteLine("hehe");}
		public static void Func106() { Console.WriteLine("hehe");}
		public static void Func107() { Console.WriteLine("hehe");}
		public static void Func108() { Console.WriteLine("hehe");}
		public static void Func109() { Console.WriteLine("hehe");}
		public static void Func110() { Console.WriteLine("hehe");}
		public static void Func111() { Console.WriteLine("hehe");}
		public static void Func112() { Console.WriteLine("hehe");}
		public static void Func113() { Console.WriteLine("hehe");}
		public static void Func114() { Console.WriteLine("hehe");}
		public static void Func115() { Console.WriteLine("hehe");}
		public static void Func116() { Console.WriteLine("hehe");}
		public static void Func117() { Console.WriteLine("hehe");}
		public static void Func118() { Console.WriteLine("hehe");}
		public static void Func119() { Console.WriteLine("hehe");}
		public static void Func120() { Console.WriteLine("hehe");}
		public static void Func121() { Console.WriteLine("hehe");}
		public static void Func122() { Console.WriteLine("hehe");}
		public static void Func123() { Console.WriteLine("hehe");}
		public static void Func124() { Console.WriteLine("hehe");}
		public static void Func125() { Console.WriteLine("hehe");}
		public static void Func126() { Console.WriteLine("hehe");}
		public static void Func127() { Console.WriteLine("hehe");}
		public static void Func128() { Console.WriteLine("hehe");}
		public static void Func129() { Console.WriteLine("hehe");}

		static Program() { 			Func0();
			Func1();
			Func2();
			Func3();
			Func4();
			Func5();
			Func6();
			Func7();
			Func8();
			Func9();
			Func10();
			Func11();
			Func12();
			Func13();
			Func14();
			Func15();
			Func16();
			Func17();
			Func18();
			Func19();
			Func20();
			Func21();
			Func22();
			Func23();
			Func24();
			Func25();
			Func26();
			Func27();
			Func28();
			Func29();
			Func30();
			Func31();
			Func32();
			Func33();
			Func34();
			Func35();
			Func36();
			Func37();
			Func38();
			Func39();
			Func40();
			Func41();
			Func42();
			Func43();
			Func44();
			Func45();
			Func46();
			Func47();
			Func48();
			Func49();
			Func50();
			Func51();
			Func52();
			Func53();
			Func54();
			Func55();
			Func56();
			Func57();
			Func58();
			Func59();
			Func60();
			Func61();
			Func62();
			Func63();
			Func64();
			Func65();
			Func66();
			Func67();
			Func68();
			Func69();
			Func70();
			Func71();
			Func72();
			Func73();
			Func74();
			Func75();
			Func76();
			Func77();
			Func78();
			Func79();
			Func80();
			Func81();
			Func82();
			Func83();
			Func84();
			Func85();
			Func86();
			Func87();
			Func88();
			Func89();
			Func90();
			Func91();
			Func92();
			Func93();
			Func94();
			Func95();
			Func96();
			Func97();
			Func98();
			Func99();
			Func100();
			Func101();
			Func102();
			Func103();
			Func104();
			Func105();
			Func106();
			Func107();
			Func108();
			Func109();
			Func110();
			Func111();
			Func112();
			Func113();
			Func114();
			Func115();
			Func116();
			Func117();
			Func118();
			Func119();
			Func120();
			Func121();
			Func122();
			Func123();
			Func124();
			Func125();
			Func126();
			Func127();
			Func128();
			Func129();
	
			FuncA0();
			FuncA1();
			FuncA2();
			FuncA3();
			FuncA4();
			FuncA5();
			
			void A1()
			{
			}
			void A2()
			{
			}
			void A3()
			{
			}
			
			void A4()
			{
			}
			
			A1();A2();A3();A4();
			
 }
	}

}

**Comment by yanghuan** [comment]
![WF)Y$A`_ DB5N%{4P2(1IK](https://user-images.githubusercontent.com/2771349/131974141-73387280-de18-44eb-a891-bfa02c931d5f.png)
