### ISSUE TITLE
参数使用out修饰时 生成的Lua代码有语法错误

### ISSUE THREAD

**Issue by kkvskkkk** [yanghuan/CSharp.lua#381]
using System;
using System.Collections.Generic;

namespace HelloLua 
{
	public static class Program 
	{
		public static Dictionary<int, string> dict = new Dictionary<int, string>()
		{
			{1, "11111"},
			{2, "22222222"}
		};
		 
		
		 public static void Main(string[] args) 
		 {
			 int i = 2;
			 string s;
			 if (dict.TryGetValue(i, out s))
			 {
				 Console.WriteLine(s);
			 }
			 
			 Console.WriteLine("haha");
		 }
	}
}

**Comment by yanghuan** [comment]
#381 修复回退了
