### ISSUE TITLE
How to create table in lua from C#

### ISSUE THREAD

**Issue by LordZEDith** [yanghuan/CSharp.lua#385]
I am wondering how I would make the compiler create a table in the lua script instead of things such as ArrayString etc.

**Comment by LordZEDith** [comment]
So I used the Bridge you have in test which has LuaArray implemented however whenever I include the dll and xml it still says it doesn't understand what toList is. In the LuaArray Code how to get around this.

**Comment by yanghuan** [comment]
You can refer to the link below
https://github.com/yanghuan/CSharp.lua/wiki/FAQ_en#7how-do-you-call-or-insert-lua-code-in-your-code
https://github.com/yanghuan/CSharp.lua/wiki/attributes_en#csharpluatemplate
