### ISSUE TITLE
DefaultInterpolatedStringHandler

### ISSUE THREAD

**Issue by Orden4** [yanghuan/CSharp.lua#405]
As of .NET 6, interpolated strings get compiled into a rather convoluted construct, like so:

```csharp
// original
return $"{this.saveFolder}\\{GetPlayerName(player)}-save-{saveSlot}{this.suffix}.pld"

// compiled
defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(11, 4);
defaultInterpolatedStringHandler.AppendFormatted(saveFolder);
defaultInterpolatedStringHandler.AppendLiteral("\\");
defaultInterpolatedStringHandler.AppendFormatted(Common.GetPlayerName(player));
defaultInterpolatedStringHandler.AppendLiteral("-save-");
defaultInterpolatedStringHandler.AppendFormatted(saveSlot);
defaultInterpolatedStringHandler.AppendFormatted(suffix);
defaultInterpolatedStringHandler.AppendLiteral(".pld");
return defaultInterpolatedStringHandler.ToStringAndClear();
```

This code won't work when transpiled because DefaultInterpolatedStringHandler isn't implemented in CSharpLua.
Normally speaking this wouldn't be a problem, but my WCSharp library is utilised by having War3Net decompile the NuGet packages and then transpiling them to Lua, which means that the code that gets used is not the code that I directly wrote, but the decompiled code.

[I've raised the topic with the creator of War3Net as well over on Hiveworkshop](https://www.hiveworkshop.com/threads/c-mapmaking-in-csharp.317839/page-7#post-3562887), but I imagine that the best solution is if DefaultInterpolatedStringHandler gets implemented in CSharpLua.

**Comment by yanghuan** [comment]
you may set ICSharpCode.Decompiler.DecompilerSettings.StringInterpolation ?

**Comment by Orden4** [comment]
That setting was for the style itself as introduced in C# 6, and not the new compiled format introduced in (apparently) C# 10.
Anyway, I've confirmed that ILSpy has already integrated the desired behaviour into the decompiler, just that it's only on the pre-release versions which War3Net currently does not use. In other words this problem will soon fix itself anyway, so no need for any changes to CSharp.lua.

Sorry for the trouble!
