### ISSUE TITLE
连续赋值的翻译错误

### ISSUE THREAD

**Issue by uncleciba** [yanghuan/CSharp.lua#411]
![image](https://user-images.githubusercontent.com/692967/215329507-d772a7e9-af82-4d34-8960-46ec8b2526da.png)
错误的翻译为
![image](https://user-images.githubusercontent.com/692967/215329533-dd81ec75-6334-4d7a-8ea1-be8bc79f2305.png)
项目的原因，我用的版本比较老

**Comment by yanghuan** [comment]
我用最新版本测试确实未发现问题
