### ISSUE TITLE
Request: Full self-compilation

### ISSUE THREAD

**Issue by InDieTasten** [yanghuan/CSharp.lua#43]
Currently, the self compilation is just high level integration test, but is of no use, because the output cannot be executed (Correct me if I'm wrong).

For it to be called self-compiling, which I think is a really good target, all of the compilers dependencies need to compile to lua too, which are currently [Microsoft.CodeAnalysis.dll](https://github.com/dotnet/roslyn/blob/version-2.4.0/src/Compilers/Core/Portable/CodeAnalysis.csproj) and [Microsoft.CodeAnalysis.CSharp.dll](https://github.com/dotnet/roslyn/blob/version-2.4.0/src/Compilers/CSharp/Portable/CSharpCodeAnalysis.csproj).

They do however have more dependencies, but if lucky, the parts to build the syntax tree do not require that many more CLR features.

**Comment by yanghuan** [comment]
Thanks for the advice.  but that would be a big work. now it just be uesd for test.
compile all dependencies  to lua, not very useful i think.

**Comment by InDieTasten** [comment]
Ok, I will try and see, if I can make it work with minimal effort. If I face bigger challenges, I guess those need to be addressed before handling full self compilation.

But I do think this will be useful. I mean what's the use of this entire project then, if it's not about compiling c# into lua. I think it would be great to go all the way 😀

**Comment by InDieTasten** [comment]
Hm, unfortunately, the compiler tools use System.Collections.Immutable from CoreFX, which in turn uses System.Threading and a ton of other types form CoreCLR. So it's not trivially portable. I will try a bit further.

I will see if I can reimplement the CodeAnalysis.CSharp package in such minimal way, that it only needs types, that you've already ported to CSharp.lua.

**Comment by yanghuan** [comment]
thread, task, await, unsafe code, and some base library not support, so compile Roslyn maybe very hard
