### ISSUE TITLE
Could you make a standalone distribution like bflat?

### ISSUE THREAD

**Issue by iahung2** [yanghuan/CSharp.lua#432]
bflat (https://github.com/bflattened/bflat) is a standalone distribution that doesn't need .NET installed to work.

**Comment by yanghuan** [comment]
This may not be appropriate，It compiles the .NET Standard Library.

**Comment by iahung2** [comment]
> This may not be appropriate，It compiles the .NET Standard Library.

Want to elaborate more? CSharp.lua itself is a .NET application. It's definitely possible to make it standalone (bundled the .NET runtime with the distribution?). It seems Visual Studio also offer the feature to deploy self-contained .NET application (I'm not sure, but this is what Google tells me, as I'm not using Visual Studio for a long time, last version I used is V2010). Yes, I know you implemented your own .NET Standard Library in Lua. But CSharp.lua itself doesn't use this library. Only applications built by CSharp.lua use this library. And my suggestion is only about CSharp.lua as the .NET application itself.

**Comment by yanghuan** [comment]
I thought about it and it might be possible. CSharp.lua needs to compile the C# code into the .net assembly first, so it will depend on the .net standard library. If you compiled CSharp.lua by aot, you need to use the -l compilation parameter to import the dll of the .net standard library

**Comment by yanghuan** [comment]
https://github.com/yanghuan/CSharp.lua/blob/master/CSharp.lua/Compiler.cs#L83
By default, it will refer to the standard library of the .net environment where CSharp.lua runs

**Comment by iahung2** [comment]
> I thought about it and it might be possible. CSharp.lua needs to compile the C# code into the .net assembly first, so it will depend on the .net standard library. If you compiled CSharp.lua by aot, you need to use the -l compilation parameter to import the dll of the .net standard library

No AOT is needed. I'm not talking about building CSharp.lua using bflat. I'm talking about creating a self-contained distribution of CSharp.lua.

> https://github.com/yanghuan/CSharp.lua/blob/master/CSharp.lua/Compiler.cs#L83 By default, it will refer to the standard library of the .net environment where CSharp.lua runs

Turned out you don't even need Visual Studio, `dotnet` offers this feature out of the box:

https://learn.microsoft.com/en-us/dotnet/core/deploying/#publish-self-contained
