### ISSUE TITLE
Note to the repository author

### ISSUE THREAD

**Issue by joelverhagen** [yanghuan/CSharp.lua#467]
(I sent this over email but I wanted to be sure it got through -- I am posting this because I am worried I am opening too many issues)

Hello Yang Huan!

I found your project CSharp.lua and I think it's amazing. It's just what I was looking for. I have some .NET code I'd like to run as a Factorio game mod. Factorio mods are implemented in Lua 5.2 so your project is a perfect fit.

I am slowly getting my FactorioTools project (https://github.com/joelverhagen/FactorioTools) and its dependencies to run as Lua. So far it's going well but I am encountering a little issues here and there. I hope it's okay that I just open the issues on the GitHub repo with minimal repros. I hope my conduct on your repo is acceptable and I do not wish to come across as critical or nitpicking. Overall the project seems amazing and I think it will work after some refactoring in my project with workarounds for bugs I have found.

I've gotten my FluteSharp project (https://github.com/joelverhagen/FluteSharp, a dependency of my FactorioTools project) working well. Itself is a port of a C library written by an academic. The fact that it is working now in Lua is very encouraging to me.

If you'd like me to provide feedback about the bugs in a different way or reduce the number of issues/PRs I am raising, please let me know. 

I have no expectation on the PRs being accepted or my bug reports being fixed. I just hope to provide feedback that can make your project better if possible.

Please let me know if I can answer any questions. 

**Update from my email:** I have my FactorioTools project compiling and importing `require("out")`. I am now working through runtime issues.

**Comment by yanghuan** [comment]
Thanks for those pr & issue,  they are very helpful.  don't be stingy with any of your feedback, I will also fix the bug as soon as possible.

**Comment by joelverhagen** [comment]
Thank you :). I'll keep pushing forward on getting my project running in Lua, as long as I can.
