### ISSUE TITLE
调用await 函数问题

### ISSUE THREAD

**Issue by mudebug77** [yanghuan/CSharp.lua#489]
![image](https://github.com/yanghuan/CSharp.lua/assets/34656102/5e24b7f3-927d-4413-bc61-368108711aa0)

        public async Task<int> Test3(int a, int b)
        {
            Console.WriteLine($"Test3:{a},{b}");
            await Task.Delay(1000);
            Console.WriteLine("Test3 End");
            return 3;
        }

这是我的代码，Test1和test2都正常
我要怎样调用Test3 并得到返回值？

**Comment by yanghuan** [comment]
int a = await Test3(1, 2);

**Comment by mudebug77** [comment]
@yanghuan 我是希望在c#代码中得到返回值，xlua环境中我得到null返回值

**Comment by yanghuan** [comment]
Test3   是C# dll中实现的，需要wrap到lua环境，怎么适配CSharp.lua的lua Task库的实现，需要自己适配了。

**Comment by mudebug77** [comment]
了解，感谢大佬解答
