### ISSUE TITLE
Enum.HasFlag bugged

### ISSUE THREAD

**Issue by Orden4** [yanghuan/CSharp.lua#511]
Consider an enum like this:
```csharp
[Flags]
public enum Test
{
 	None = 0,
	A = 1,
	B = 2,
	C = 4,
}
```
Using this enum, some scenarios in both C# and Lua:
| Statement                                    | C#    | Lua   |
|----------------------------------------------|-------|-------|
| Test.None.HasFlag(Test.None)                 | true  | true  |
| Test.None.HasFlag(Test.A)                    | false | false |
| Test.A.HasFlag(Test.None)                    | true  | false |
| Test.A.HasFlag(Test.A)                       | true  | true  |
| Test.A.HasFlag(Test.A \| Test.B)             | true  | false |
| (Test.A \| Test.B).HasFlag(Test.A)           | true  | true  |
| (Test.A \| Test.B).HasFlag(Test.A \| Test.C) | false | true  |

According to the [official Microsoft documents](https://learn.microsoft.com/en-us/dotnet/api/system.enum.hasflag?view=net-8.0#remarks), the correct code for the `HasFlag` operation should simply be `(this & flag) == flag`, rather than the current code.

**Comment by yanghuan** [comment]
thanks, but Test.A.HasFlag(Test.A | Test.B)  should be false
