### ISSUE TITLE
运行出错 ,如何解决？

### ISSUE THREAD

**Issue by xxlyyr** [yanghuan/CSharp.lua#6]
Unhandled Exception: System.IO.FileNotFoundException: could not load file or assembly 'Microsoft.CodeAnalysis, Version=1.3.1.0,Culture=neutral,PublicKeyToken=31bf3856ad364e35' or one of its dependencies.系统找不到指定文件。
at CSharpLua.Program.Main<string[] args>

**Comment by yanghuan** [comment]
额,你需要编译一下，一般来说编译时会自动下载缺失的NuGet包,里面有Microsoft.CodeAnalysis.dll，也可以点击解决方案右键->
还原NuGet包。

2017-03-22 11:56 GMT+08:00 xxlyyr <notifications@github.com>:
