### ISSUE TITLE
support for json and web requests 

### ISSUE THREAD

**Issue by risheelk** [yanghuan/CSharp.lua#66]
i want to write c# which contain rest api, and convert it to lua code.
when i try to convert i got errors.

Sample code

`using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers; 

namespace ConsoleProgram
{
    public class DataObject
    {
        public string Name { get; set; }
    }

    public class Class1
    {
        private const string URL = "https://sub.domain.com/objects.json";
        private string urlParameters = "?api_key=123";

        static void Main(string[] args)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(URL);

            // Add an Accept header for JSON format.
            client.DefaultRequestHeaders.Accept.Add(
            new MediaTypeWithQualityHeaderValue("application/json"));

            // List data response.
            HttpResponseMessage response = client.GetAsync(urlParameters).Result;  // Blocking call! Program will wait here until a response is received or a timeout occurs.
            if (response.IsSuccessStatusCode)
            {
                // Parse the response body.
                var dataObjects = response.Content.ReadAsAsync<IEnumerable<DataObject>>().Result;  //Make sure to add a reference to System.Net.Http.Formatting.dll
                foreach (var d in dataObjects)
                {
                    Console.WriteLine("{0}", d.Name);
                }
            }
            else
            {
                Console.WriteLine("{0} ({1})", (int)response.StatusCode, response.ReasonPhrase);
            }

            //Make any other calls using HttpClient here.

            //Dispose once all HttpClient calls are complete. This is not necessary if the containing object will be disposed of; for example in this case the HttpClient instance will be disposed automatically when the application terminates so the following call is superfluous.
            client.Dispose();
        }
    }
}`

Please add support for .net http and json

**Comment by yanghuan** [comment]
your code is not correct. i test this code, it can work
```
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace Test {
  public class DataObject {
    public string Name { get; set; }
  }

  public class Program {
    private const string URL = "https://sub.domain.com/objects.json";
    private const string urlParameters = "?api_key=123";

    public static void Main(string[] args) {
      HttpClient client = new HttpClient();
      client.BaseAddress = new Uri(URL);

      // Add an Accept header for JSON format.
      client.DefaultRequestHeaders.Accept.Add(
      new MediaTypeWithQualityHeaderValue("application/json"));

      // List data response.
      HttpResponseMessage response = client.GetAsync(urlParameters).Result;  // Blocking call! Program will wait here until a response is received or a timeout occurs.
      if (response.IsSuccessStatusCode) {
        // Parse the response body.
        var dataObjects = response.Content.ReadAsAsync<IEnumerable<DataObject>>().Result;  //Make sure to add a reference to System.Net.Http.Formatting.dll
        foreach (var d in dataObjects) {
          Console.WriteLine("{0}", d.Name);
        }
      } else {
        Console.WriteLine("{0} ({1})", (int)response.StatusCode, response.ReasonPhrase);
      }

      //Make any other calls using HttpClient here.

      //Dispose once all HttpClient calls are complete. This is not necessary if the containing object will be disposed of; for example in this case the HttpClient instance will be disposed automatically when the application terminates so the following call is superfluous.
      client.Dispose();
    }
  }

  public static class Extension {
    public static Task<T> ReadAsAsync<T>(this HttpContent t) {
      return null;
    }
  }
}
```
will get
```
-- Generated by CSharp.lua Compiler
local System = System
local SystemNetHttp = System.Net.Http
local SystemNetHttpHeaders = System.Net.Http.Headers
local Test
System.usingDeclare(function (global)
  Test = global.Test
end)
System.namespace("Test", function (namespace)
  namespace.class("DataObject", function (namespace)
    return {}
  end)

  namespace.class("Program", function (namespace)
    local URL, Main
    URL = "https://sub.domain.com/objects.json"
    Main = function (args)
      local client = SystemNetHttp.HttpClient()
      client:setBaseAddress(System.Uri(URL))

      -- Add an Accept header for JSON format.
      client:getDefaultRequestHeaders():getAccept():Add(SystemNetHttpHeaders.MediaTypeWithQualityHeaderValue("application/json"))

      -- List data response.
      local response = client:GetAsync("?api_key=123" --[[Program.urlParameters]]):getResult()
      -- Blocking call! Program will wait here until a response is received or a timeout occurs.
      if response:getIsSuccessStatusCode() then
        -- Parse the response body.
        local dataObjects = Test.Extension.ReadAsAsync(response:getContent(), System.IEnumerable_1(Test.DataObject)):getResult()
        --Make sure to add a reference to System.Net.Http.Formatting.dll
        for _, d in System.each(dataObjects) do
          System.Console.WriteLine("{0}", d.Name)
        end
      else
        System.Console.WriteLine("{0} ({1})", response:getStatusCode(), response:getReasonPhrase())
      end

      --Make any other calls using HttpClient here.

      --Dispose once all HttpClient calls are complete. This is not necessary if the containing object will be disposed of; for example in this case the HttpClient instance will be disposed automatically when the application terminates so the following call is superfluous.
      client:Dispose()
    end
    return {
      Main = Main
    }
  end)

  namespace.class("Extension", function (namespace)
    local ReadAsAsync
    ReadAsAsync = function (t, T)
      return nil
    end
    return {
      ReadAsAsync = ReadAsAsync
    }
  end)
end)

```

**Comment by risheelk** [comment]
i wrote a simple web request and got An unexpected error ocurred... please try again later.

`using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System;
using System.Web;
using System.Net;
using System.IO;
using System.Threading.Tasks;
using System.Security.Cryptography.X509Certificates;
using System.Net.Security;

namespace RestApp
{
	public class RestApi
	{
       
			public static async Task<string> GetWeather()
		{
			ServicePointManager.ServerCertificateValidationCallback =
				delegate(object s, X509Certificate certificate,
					X509Chain chain, SslPolicyErrors sslPolicyErrors)
			{ return true; };

			string url = "https://api.coinmarketcap.com/v2/ticker/1/";
			HttpWebRequest request = (HttpWebRequest)WebRequest.Create(url);
			HttpWebResponse response = (HttpWebResponse)(await request.GetResponseAsync());
			StreamReader reader = new StreamReader(response.GetResponseStream());
			string jsonResponse = reader.ReadToEnd ();
			return jsonResponse;
		}
	}
    
}`

**Comment by yanghuan** [comment]
now await, async not support, Because Lua is a single threaded environment, 
The future will implement a single-threaded taskScheduler to support task, 
This priority and urgency are not high

**Comment by risheelk** [comment]
I have did some research about concurrency in lua haven't found any thing other than torch and some other lib which are not actively maintained.
Thanks for awesome lib.
