### ISSUE TITLE
只支持用.net的类库吗？

### ISSUE THREAD

**Issue by iRaynaa** [yanghuan/CSharp.lua#7]
如果我想包含UnityEngine.dll，用这个里面的结构怎么把c# To lua。
Error exception: The type of namespace name 'UnityEngine' could not be found <are you missing a using directive or assembly reference ?>

尝试把UnityEngine.dll import到了CSharp.lua的sln里面，然并卵。求解?

**Comment by yanghuan** [comment]
你需要看下命令行参数，可以参考下
https://github.com/yanghuan/CSharp.lua/blob/master/test/self-compiling/self.bat
通过命令行参数 “-l” 加入一些库的引用

2017-03-22 14:44 GMT+08:00 xxlyyr <notifications@github.com>:

**Comment by yanghuan** [comment]
CSharp.lua的文档暂时没有更新，可以参考bridge.lua的文档，他们的cmd 命令行参数基本上都是一致的
https://github.com/yanghuan/bridge.lua/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E7%AD%94#3%E5%A6%82%E6%9E%9C%E4%BD%BF%E7%94%A8%E5%88%B0%E4%BA%86%E9%99%A4%E5%9F%BA%E7%A1%80%E7%B1%BB%E5%BA%93%E4%BB%A5%E5%A4%96%E7%9A%84%E6%80%8E%E4%B9%88%E5%8A%9E

2017-03-22 14:48 GMT+08:00 杨欢 <sy.yanghuan@gmail.com>:

**Comment by iRaynaa** [comment]
ok了，CSharp.lua.exe -s [ ] -d [ ] -l [****.dll] ，谢谢。
