### ISSUE TITLE
单元测试用例执行失败

### ISSUE THREAD

**Issue by mybios** [yanghuan/CSharp.lua#93]
D:\src\CSharp.lua\test\TestCases>"../__bin/lua5.1/lua" launcher.lua
TestClass Start : NewUILoginTest
TestCase : Test
../__bin/lua5.1/lua: .\out\Tests\UIPage.lua:74: attempt to index field '__base__
' (a nil value)
stack traceback:
        .\out\Tests\UIPage.lua:74: in function '__ctor__'
        ../../CSharp.lua/Coresystem.lua/CoreSystem\Core.lua:50: in function 'New
UILoginPage'
        .\out\Tests\UIPage.lua:90: in function 'Invoke'
        .\out\TestBase\StaticTestUnit.lua:36: in function 'Run'
        launcher.lua:6: in main chunk
        [C]: at 0x00402a57

**Comment by yanghuan** [comment]
fix 890dd339f408d4d958fc697fafabc3b5d737ea8f
